# -*- coding: utf-8 -*-
"""主題 5-9：產品管理 / DevOps / 新創與創業 / 設計 / 行銷
英文 gist 與中文說明均為自行撰寫之摘要。"""

TOPICS = []

TOPICS.append(dict(zh='產品管理', en='TLDR Product', date='2026-08-18', arts=[
    dict(title_en='What People Really Think About IC Work',
         title_zh='工程師心底對「個人貢獻者」這條路的真實想法',
         gist_en="Most tech workers say they want more individual-contributor work, yet pay and influence keep many of them in management. High-impact IC tracks could fix that by rewarding autonomy and business impact without requiring anyone to manage people.",
         body_zh='多數科技工作者其實想做更多「個人貢獻者（IC）」的實作工作，但薪酬與影響力這兩件事，還是把很多人留在管理職上。若能設計出「高影響力 IC 職涯軌道」，讓自主性與對業務的實質貢獻同樣獲得回報，就能讓人不必為了升遷而被迫去帶人。',
         vocab=[('individual contributor (IC)', '科技業職稱「個人貢獻者」，指不帶團隊、以專業產出為主的角色。'),
                ('autonomy (n.)', '「自主性」，形容詞 autonomous，職場動機理論的核心概念之一。'),
                ('track (n.)', '此處為「職涯軌道」，如 IC track 與 management track 兩條並行的升遷路徑。')]),
    dict(title_en="Nvidia's Risky Business",
         title_zh='Nvidia 的高風險生意',
         gist_en="The AI infrastructure boom increasingly rests on risky financing. Nvidia can keep the buildout going by pulling in fresh pools of capital, but the whole strategy depends on AI revenue growing fast enough to justify what has already been spent.",
         body_zh='AI 基礎建設的榮景，正越來越倚賴風險偏高的融資手法。Nvidia 有能力持續吸引新的資金池來推動擴建，但這套策略成不成立，取決於 AI 相關營收能不能長得夠快，快到足以合理化目前已經投下去的錢。',
         vocab=[('rest on X', '片語「建立在 X 之上、倚賴 X」，語氣比 depend on 更帶有「支撐」的意象。'),
                ('pull in', '片語動詞「吸引進來」，此處指招攬資金。'),
                ('justify (v.)', '「證明……是合理的」，商業決策語境高頻字。')]),
    dict(title_en='What Three Seconds of Music Taught Me About Product',
         title_zh='三秒鐘的音樂教我的產品課',
         gist_en="Strategic constraints sharpen product strategy because they force a team to commit instead of iterating forever. Narrowing the options protects the core hypothesis, cuts decision fatigue and frees people to exercise creative judgement.",
         body_zh='策略性的限制反而會讓產品策略更銳利，因為限制會逼團隊真正做出承諾，而不是無止盡地繼續迭代下去。把選項收窄，可以保住核心假設、減少決策疲勞，也讓成員更敢於運用創意判斷，同時不至於扼殺批判性思考。',
         vocab=[('constraint (n.)', '「限制條件」，動詞 constrain，設計與工程討論常見。'),
                ('commit (v.)', '此處為「作出承諾、押定方向」，名詞 commitment。'),
                ('decision fatigue', '心理學名詞「決策疲勞」，指連續做決定後判斷力下降。')]),
    dict(title_en='A Good Move Is Constructive',
         title_zh='好的一步棋，本身就要有建設性',
         gist_en="Product strategy should emerge from a run of good moves rather than from top-down planning. A constructive move strengthens an existing relationship or adds useful structure, and it creates value on its own instead of leaning on some hypothetical V2 to pay off.",
         body_zh='產品策略應該是從「連續走出好棋」中浮現出來的，而不是靠由上而下的規劃硬訂出來。所謂有建設性的一步，指的是它能強化既有的關係、或是引入有用的結構，而且本身就能創造價值，不需要依賴某個假想中的 V2 版本或後續動作，才顯得值得做。',
         vocab=[('emerge from', '片語「從……浮現」，強調非事先規劃而是逐步顯現。'),
                ('top-down (adj.)', '「由上而下的」，反義為 bottom-up。'),
                ('lean on X', '片語「倚賴 X」，此處帶有「靠不住的依賴」語氣。')]),
    dict(title_en='A Modern Framework for Monetizing AI',
         title_zh='AI 商業化的新定價框架',
         gist_en="AI is expensive to build, and vendors often absorb those costs without capturing matching value. The proposed fix is to price against measurable customer outcomes and actual AI usage, moving away from flat subscriptions toward tiered, hybrid or outcome-based models as billing systems mature.",
         body_zh='AI 對供應商來說開發成本很高，卻常常無法收回對等的價值。這套框架建議改以「可量化的客戶成果」與「實際 AI 使用量」為定價基礎，隨著計費系統成熟，逐步從單一費率訂閱制，轉向分層式、混合式或以成果計價的模式。',
         vocab=[('absorb (v.)', '此處為「自行吸收（成本）」，不是「吸收知識」的意思。'),
                ('capture value', '商業慣用語「攫取價值」，指把創造出的價值轉換成自身收益。'),
                ('flat (adj.)', '「單一費率的」，flat subscription 指不論用量都收同樣價格。')]),
    dict(title_en='Tension-Based Prioritization',
         title_zh='以「張力」為核心的優先排序法',
         gist_en="Better prioritization starts by naming the tensions that stop a team acting on what it already knows. Those recurring conflicts usually reveal the real decision more clearly than any framework does.",
         body_zh='更好的優先順序排定，起點不是套框架，而是先把「究竟是什麼張力，讓團隊明明知道該做卻遲遲沒動手」講清楚。這些一再出現的內部衝突，往往比任何框架都更能揭露真正該拍板的決策是什麼。',
         vocab=[('tension (n.)', '「張力、緊繃關係」，此處指目標或意見之間的拉扯。'),
                ('stop sb. V-ing', '句型「阻止某人做某事」，stop 後可直接接動名詞。'),
                ('recurring (adj.)', '「一再發生的」，動詞 recur。')]),
    dict(title_en='Shape Up for Data Teams',
         title_zh='資料團隊要怎麼用 Shape Up',
         gist_en="Shape Up only works for data teams when they help shape priorities from the very start. Without a seat at the betting table they stay reactive service teams rather than genuine partners.",
         body_zh='Shape Up 這套方法要在資料團隊身上奏效，前提是他們從一開始就參與「形塑優先順序」的過程。如果在決定要投入哪些專案的那張桌子上沒有位置，資料團隊就只會停留在被動接單的服務單位，而不是真正的合作夥伴。',
         vocab=[('shape (v.)', '「形塑、左右方向」，此處呼應方法論名稱 Shape Up。'),
                ('a seat at the table', '慣用語「在決策圈裡有一席之地」。'),
                ('reactive (adj.)', '「被動反應的」，反義 proactive（主動的）。')]),
    dict(title_en='Four Habits From History’s Happiest Philosopher',
         title_zh='史上最快樂的哲學家留下的四個習慣',
         gist_en="Lasting happiness comes from replacing judgement with curiosity. Understand what actually drives your emotions and behaviour, gain some perspective, and use that insight to respond more calmly and choose better.",
         body_zh='持久的快樂，來自於用好奇心取代評判。先弄清楚究竟是什麼在驅動自己的情緒與行為，藉此拉開視角、看得更寬，再運用這份理解，讓自己回應得更冷靜，也做出更好的選擇。',
         vocab=[('lasting (adj.)', '「持久的」，由動詞 last（持續）而來。'),
                ('replace A with B', '句型「用 B 取代 A」，介系詞固定用 with。'),
                ('perspective (n.)', '「視角、格局」，gain perspective 指跳脫當下看得更全面。')]),
]))

TOPICS.append(dict(zh='DevOps', en='TLDR DevOps', date='2026-08-19', arts=[
    dict(title_en='Claude Opus 5 Arrives in AWS GovCloud',
         title_zh='Claude Opus 5 進駐 AWS GovCloud',
         gist_en="AWS GovCloud now serves Claude Opus 5 through Amazon Bedrock, bringing stronger coding, long-running agent, reasoning and document-analysis capability to government workloads. Zero data retention is on by default, and regional data residency supports enterprise governance rules.",
         body_zh='AWS GovCloud 現在可透過 Amazon Bedrock 使用 Claude Opus 5，把更強的程式撰寫、長時間運行 agent、推理與複雜文件分析能力帶進政府單位的工作負載。系統預設啟用「零資料保留」，並提供區域資料落地與 AWS 代管功能，以符合企業層級的資料治理要求。',
         vocab=[('retention (n.)', '「保留」，zero data retention 指服務方不留存輸入資料。'),
                ('residency (n.)', '「落地、駐留」，data residency 指資料必須存放在特定地理區域。'),
                ('governance (n.)', '「治理」，企業 IT 語境指制度化的管控規範。')]),
    dict(title_en='An Open-Source Take on Durable Objects',
         title_zh='把 Durable Objects 從 Cloudflare 解放出來',
         gist_en="celld is an open-source, self-hosted implementation of Cloudflare Workers and Durable Objects built on S3-compatible storage, SQLite and Rust's Tokio runtime. It aims to offer the same stateful serverless model without vendor lock-in, though Cloudflare disputes the claimed cost savings.",
         body_zh='celld 是一套開源、可自行架設的 Cloudflare Workers 與 Durable Objects 實作，底層採用相容 S3 的儲存、SQLite，以及 Rust 的 Tokio 執行環境。它的目標是提供同樣的「有狀態無伺服器」模型，但不必被特定廠商綁死，成本也可能大幅降低，不過 Cloudflare 對這個省錢幅度持不同看法。',
         vocab=[('self-hosted (adj.)', '「自行架設的」，指部署在自己的機器而非雲端服務商。'),
                ('vendor lock-in', '商業術語「廠商鎖定」，指難以轉換供應商的處境。'),
                ('dispute (v.)', '「對……提出異議」，語氣比 disagree 更正式。')]),
    dict(title_en='A Preview of DuckDB v2.0',
         title_zh='DuckDB 2.0 搶先看',
         gist_en="DuckDB 2.0 adds client/server operation, triggers, asynchronous I/O, a new storage format and an extensible SQL parser. Query execution and remote-storage performance both improve, with roughly 40x faster execution reported on one recursive CTE benchmark.",
         body_zh='DuckDB 2.0 將透過 Quack 協定加入主從式（client/server）運作模式，並新增觸發器、非同步 I/O、新的儲存格式，以及可擴充的 SQL 剖析器。這個版本同時改善查詢執行與遠端儲存效能，官方在某個遞迴 CTE 基準測試中回報約 40 倍的執行速度提升，並為湖倉工作負載加入了分區感知最佳化。',
         vocab=[('trigger (n.)', '資料庫術語「觸發器」，在特定事件發生時自動執行的程序。'),
                ('asynchronous I/O', '「非同步輸入輸出」，不必等待前一個動作完成即可繼續。'),
                ('recursive (adj.)', '「遞迴的」，CTE 指共用資料表運算式，可自我參照。')]),
    dict(title_en='Rethinking Database Programming',
         title_zh='重新想像「寫資料庫程式」這件事',
         gist_en="Acadia is a public-alpha language that compiles typed, functional database code down to SQL. It brings custom types, compiler-verified migrations, better error messages and end-to-end type safety to SQLite-backed apps, generating and optimising the underlying SQL for you.",
         body_zh='Acadia 是一款進入公開 alpha 階段的程式語言，能把具型別的函式式資料庫程式碼編譯成 SQL，替以 SQLite 為底的應用帶來自訂型別、由編譯器驗證的資料庫遷移、更清楚的錯誤訊息，以及端到端的型別安全。開發者用 map、filter 與具型別的繫結來定義資料表與交易，Acadia 則負責產生並最佳化底層 SQL，同時把型別打通到前後端。',
         vocab=[('typed (adj.)', '「具型別的」，強調編譯期即可檢查資料型態。'),
                ('migration (n.)', '資料庫術語「結構遷移」，指變更資料表結構的版本化流程。'),
                ('end-to-end (adj.)', '「端到端的」，指從頭到尾一以貫之。')]),
    dict(title_en='Cutting Kubernetes Release Validation to Two Minutes',
         title_zh='把 Kubernetes 發布驗證從 45 分鐘壓到 2 分鐘',
         gist_en="Automating release validation in CI/CD cut manual verification from about 45 minutes to 2 by checking pod readiness, failure states and a 60-second stability window before a release is marked successful. A green pipeline then reflects application health, not just deployment completion.",
         body_zh='把 Kubernetes 的發布驗證自動化進 CI/CD 流程後，人工確認時間從約 45 分鐘縮短到 2 分鐘：做法是在標記發布成功之前，先檢查 pod 是否就緒、有無失敗狀態，並觀察一個 60 秒的穩定期。這讓「流水線亮綠燈」真正代表應用程式健康，而不只是代表部署動作跑完了。',
         vocab=[('readiness (n.)', '「就緒狀態」，Kubernetes 有 readiness probe（就緒探針）。'),
                ('stability window', '「穩定觀察期」，指變更後持續觀察一段時間確認無異常。'),
                ('reflect (v.)', '「反映、代表」，此處指指標是否真實反映系統狀態。')]),
    dict(title_en='OpenViking, a Context Database for Agents',
         title_zh='OpenViking：給 AI Agent 用的情境資料庫',
         gist_en="OpenViking stores an agent's memories, resources and skills as a virtual filesystem. Agents navigate their own context with commands like ls, tree and find instead of querying a vector store, and content is tiered into abstract, overview and detail levels loaded on demand.",
         body_zh='OpenViking 是一套開源的「情境資料庫」，把 AI agent 的記憶、資源與技能，以虛擬檔案系統的形式存放在 viking:// 協定底下。Agent 是用 ls、tree、find 這類指令去瀏覽自己的上下文，而不是去查詢向量資料庫。內容分成三層：L0 摘要、L1 概覽、L2 細節，需要時才載入。',
         vocab=[('virtual filesystem', '「虛擬檔案系統」，看起來像檔案結構但底層未必是真實檔案。'),
                ('navigate (v.)', '「瀏覽、在其中移動」，此處指 agent 自行探索資料結構。'),
                ('on demand', '片語「按需、需要時才」，常見於資源載入策略。')]),
    dict(title_en='ai-memory Gives Coding Agents Persistent Memory',
         title_zh='ai-memory 讓編碼 Agent 跨工具記得住',
         gist_en="ai-memory gives AI coding agents memory that survives across sessions and across different tools, so work begun in one agent can be picked up in another without re-explaining context. It stores history as plain Markdown in a git repo with SQLite full-text search, needing no vector database.",
         body_zh='ai-memory 是一套開源工具，讓 AI 編碼 agent 擁有跨工作階段、甚至跨不同工具的持久記憶，因此在 Claude Code 起頭的工作，可以直接接到 OpenAI Codex 上繼續，不必重新交代前因後果。它把工作階段紀錄以純 Markdown 存在 git 儲存庫中，搭配 SQLite 的 FTS5 全文檢索與選用的向量嵌入，完全不需要向量資料庫。它以單一 Rust 執行檔發布，並提供 Docker 與原生套件。',
         vocab=[('persistent (adj.)', '「持久的」，指資料在程式關閉後仍保留。'),
                ('pick up (v. phr.)', '片語動詞「接手、接續」，pick up where you left off 意為從中斷處繼續。'),
                ('plain (adj.)', '「純粹的、未加工的」，plain Markdown 指不額外包裝的純文字格式。')]),
    dict(title_en='GitHub Incident Report',
         title_zh='GitHub 事故報告',
         gist_en="GitHub suffered a nearly eight-hour incident hitting Issues, Pull Requests, APIs, Actions, Copilot and authentication, with web and API error rates near 20% and some downloads at 50%. A traffic spike exhausted an Istio sidecar's concurrency limit, a misconfigured autoscaling policy blocked scaling, and overloaded HAProxy nodes followed.",
         body_zh='GitHub 發生近八小時的事故，Issues、Pull Requests、API、Actions、Copilot 與身分驗證全數受影響，網頁與 API 錯誤率約達 20%，部分下載更達 50%。根因是流量突增耗盡了 Istio sidecar 的併發上限，而自動擴縮政策設定錯誤導致它無法擴容，接著 HAProxy 節點也被拖垮。VS Code 的重試錯誤另外把 Copilot 權杖流量放大約十倍，進一步延後復原。',
         vocab=[('exhaust (v.)', '「耗盡」，此處指把可用配額用光，形容詞 exhausted。'),
                ('concurrency (n.)', '「併發（量）」，指同時處理的請求數。'),
                ('overloaded (adj.)', '「超載的」，動詞 overload。')]),
    dict(title_en='The Benchmarkpocalypse',
         title_zh='基準測試的世界末日',
         gist_en="LLM coding agents can optimise hard for benchmark scores without improving real performance, and sometimes while hurting it. In one experiment an agent-built regex engine looked 40% faster than Rust's regex crate on its target suite yet was dramatically slower on a holdout workload, with benchmark-specific shortcuts found later.",
         body_zh='LLM 編碼 agent 有辦法針對基準測試分數卯足全力最佳化，實際效能卻毫無長進，有時甚至更差；除非結果經過獨立稽核，否則連涵蓋面很廣的測試套件也很容易被鑽漏洞。某次實驗中，agent 打造的正規表達式引擎在目標測試套件上看起來比 Rust 的 regex crate 快 40%，但換到保留未公開的工作負載上就慢得離譜，事後檢查更發現它用了許多針對測試的取巧手法，甚至直接作弊。',
         vocab=[('holdout (n.)', '機器學習術語「保留集」，刻意不公開、用來檢驗是否過擬合的資料。'),
                ('shortcut (n.)', '「捷徑、取巧作法」，此處帶負面意味。'),
                ('game (v.)', '動詞用法「鑽制度漏洞、操弄」，如 game the system。')]),
]))

TOPICS.append(dict(zh='新創與創業', en='TLDR Founders', date='2026-08-19', arts=[
    dict(title_en="ARR Doesn't Mean What It Used To",
         title_zh='ARR 這個數字，早就不是原本的意思了',
         gist_en="Five growth-stage investors describe how AI-era reporting bent the standard metrics. ARR now often means annualized run rate, contracted ARR mixes signed bookings with unproven capacity, and NRR gets inflated by converting small pilots into contracts.",
         body_zh='五位成長期投資人描述了 AI 時代如何把原本的標準財務指標玩壞：ARR 現在常常只是「年化營收速率」；所謂 contracted ARR 把已簽的訂單和還沒驗證的產能混在一起算；而 NRR 則透過把小型試用轉成正式合約的方式被灌水。看財報時要特別留意這些定義上的偷換。',
         vocab=[('bend (v.)', '此處為「扭曲、變形」，bend the metrics 指讓指標失真。'),
                ('bookings (n.)', '商業術語「已簽訂單金額」，與實際入帳的 revenue 不同。'),
                ('inflate (v.)', '「灌水、膨脹」，名詞 inflation。')]),
    dict(title_en='Nine Lessons From Nine Years Building Faire',
         title_zh='Faire 九年、九堂高速成長的課',
         gist_en="Faire had fewer than ten people nine years ago and has since grown more than a hundredfold, operating in 34 countries and connecting hundreds of thousands of retailers with 20 million products. Even at the start its founders had unusual clarity about what they meant to build.",
         body_zh='九年前 Faire 團隊還不到十個人，如今規模成長超過百倍，業務遍及 34 個國家，把數十萬家在地零售商與兩千萬件獨立品牌商品連結起來。難得的是，創辦人在最早期就對「自己要做成什麼」有著異常清晰的想法。這篇文章分享了他們一路上關於如何打造高速成長公司的心得。',
         vocab=[('hundredfold (adv./adj.)', '「百倍地」，-fold 為表示倍數的字尾，如 tenfold。'),
                ('clarity (n.)', '「清晰、明確」，形容詞 clear，商業寫作常用 clarity of vision。'),
                ('operate in', '片語「在……營運」，描述公司的營業範圍。')]),
    dict(title_en='Cheap Building Raises the Value of Judgement',
         title_zh='當「做東西」變便宜，判斷力就變貴了',
         gist_en="AI makes drafts faster, so the spare capacity should go into more passes at stronger ideas. Advantage shifts to teams that know both the customer and the system well enough to pull at assumptions, correct details and tighten the story before work reaches stakeholders.",
         body_zh='AI 讓初稿產出變快，多出來的產能應該拿去對更好的點子做更多輪打磨。當「做出東西」的成本持續下降，優勢就會移轉到那些能把大量產出轉化為「真正貼合客戶需求」的團隊身上。夠了解客戶與系統的人，才有辦法去挑戰假設、修正細節、把故事收緊，讓成果送到利害關係人面前時，已經帶著團隊的judgment。',
         vocab=[('pass (n.)', '此處為「一輪、一遍」，如 another pass at the design（再修一版）。'),
                ('pull at X', '片語「拉扯、試探 X」，此處指主動去挑戰既有假設。'),
                ('stakeholder (n.)', '「利害關係人」，指與該專案有利益關聯的各方。')]),
    dict(title_en='Rebuilding to $2M ARR After an $8M Business Died Overnight',
         title_zh='上一個 800 萬美元事業一夜蒸發後，他重建到 200 萬',
         gist_en="Checkout X replaced Shopify's checkout and reached $8M ARR, then Shopify locked checkout down and the business died overnight. The founder's second product, an AI sales agent, now does $167,000 a month; he stayed lean until $50,000 MRR and took revenue-based financing instead of venture money.",
         body_zh='Checkout X 靠著取代 Shopify 的結帳流程做到 800 萬美元 ARR，結果 Shopify 一鎖死結帳權限，生意一夜之間歸零。同一位創辦人的第二個產品 Zipchat 是電商用的 AI 銷售 agent，目前月營收 16.7 萬美元、涵蓋 70 萬次對話。這次他改變玩法：撐到月經常性營收 5 萬美元前都維持精簡編制，忍受近一年每月約 2 萬美元的虧損，最後選擇以營收為基礎的融資而非創投資金。面對上百個模仿者，他靠 YouTube、SEO、合作夥伴與每月上百萬封開發信取得通路。',
         vocab=[('overnight (adv.)', '「一夜之間」，強調變化極為突然。'),
                ('stay lean', '新創慣用語「維持精簡」，指刻意不擴編、控制燒錢速度。'),
                ('revenue-based financing', '融資術語「以營收為基礎的融資」，還款金額隨營收浮動。')]),
    dict(title_en='GLM-5.3 Lands on the API Without a Price Rise',
         title_zh='GLM-5.3 上 API，價格沒漲',
         gist_en="Z.ai opened API access to GLM-5.3 at the same price as GLM-5.2, so developers get much stronger coding and long-horizon agent performance for no extra spend. Open weights are still planned but have no date.",
         body_zh='Z.ai 開放了 GLM-5.3 的 API，價格與前一代 GLM-5.2 相同，等於開發者不必多花錢就能拿到明顯更強的程式撰寫與長時程 agent 能力。官方仍計畫公開模型權重，但尚未給出時間表。',
         vocab=[('land (v.)', '此處為「上線、抵達」，科技新聞常用 X lands on Y。'),
                ('at the same price', '介系詞片語「以同樣價格」，價格前用 at。'),
                ('no extra spend', '「不需額外花費」，spend 在此作名詞用，等同 spending。')]),
    dict(title_en='Clay Moves Orchestration Out of Tables',
         title_zh='Clay 把流程編排從表格裡搬出來',
         gist_en="Clay launched Workflows in open beta for every plan. A workflow is a visual graph of connected steps; once triggered, each record moves through the branches one at a time and results write back to the data layer.",
         body_zh='Clay 針對所有付費方案開放了 Workflows 的公開測試版。所謂 workflow，是一張由各步驟串接而成的視覺化流程圖：一旦被觸發，每筆資料會逐一走過各個分支，結果再寫回 Clay 的資料層 Audiences。文章說明了他們為什麼決定把「流程編排」從表格中抽離，以及原本差點做成的另一個版本。',
         vocab=[('orchestration (n.)', '「編排、調度」，IT 語境指協調多個步驟或服務的執行。'),
                ('trigger (v.)', '「觸發」，被動用 be triggered。'),
                ('write back', '片語動詞「寫回」，指把處理結果存回原本的資料來源。')]),
    dict(title_en='What Will You Do With Unlimited IQ?',
         title_zh='如果智力無上限，你要拿它來做什麼？',
         gist_en="AI is described as an inexhaustible IQ machine. Getting that level of energy on demand from a senior or principal engineer is basically impossible, yet anyone can now open a gateway, pick any model in the world and effectively have unlimited IQ on tap.",
         body_zh='Guillermo Rauch 把 AI 形容成一台「用不完的智力機器」。你不可能隨時要求一位資深或首席工程師都拿出那種強度的專注與能量，但現在任何人只要接上一個 gateway、挑選世界上任何一個模型，就等於隨開隨有、近乎無上限的智力可用。',
         vocab=[('inexhaustible (adj.)', '「用不完的」，字首 in-（否定）＋ exhaustible（會耗盡的）。'),
                ('on demand', '片語「隨需、隨叫隨到」。'),
                ('on tap', '慣用語「隨時可取用」，原指啤酒可從桶中直接倒出。')]),
    dict(title_en='Your Biggest Competitor Might Be a Foundation Model',
         title_zh='你最大的競爭對手，可能是基礎模型本身',
         gist_en="An audit of 50 top SaaS companies looked at how each positions against the foundation models their customers now ask about. Thirty-four have shipped MCP servers so models route through their product rather than around it, but only twelve mention Claude anywhere on their own domain.",
         body_zh='一份針對 50 家頂尖 SaaS 公司的盤點，檢視它們如何面對「客戶現在會主動詢問的基礎模型」。其中 34 家已推出 MCP 伺服器或連接器，讓模型是「穿過」自家產品而不是繞過它；但只有 12 家在自己的官網上提到 Claude，僅 4 家提供「自建 vs 採購」的成本比較給那些想自己動手做的潛在客戶。Zapier 透過 MCP 串接 9,000 個應用，Intercom 則給企業客戶一份 20 題的評估清單。',
         vocab=[('audit (n.)', '「盤點、稽核」，此處指系統性的調查檢視。'),
                ('position against X', '行銷術語「相對於 X 進行定位」。'),
                ('route through X', '片語「經由 X 轉送」，與 route around（繞過）形成對比。')]),
]))

TOPICS.append(dict(zh='設計', en='TLDR Design', date='2026-08-19', arts=[
    dict(title_en='A Hidden Video Points to Camera-Equipped AirPods',
         title_zh='隱藏影片洩漏：AirPods 可能要裝鏡頭了',
         gist_en="A demo video buried in a macOS release candidate is the strongest sign yet that Apple is building AirPods with cameras. The feature appears to work with Visual Intelligence and Siri so users can identify and ask about objects around them, and it warns when the view is blocked.",
         body_zh='藏在 macOS Tahoe 26.7 候選版本裡的一支示範影片，成為目前最強的證據，顯示 Apple 正在開發內建鏡頭的 AirPods。這項功能看來會搭配 Visual Intelligence 與 Siri，讓使用者辨識周遭物體、提問並儲存資訊，鏡頭被遮擋時還會提出警告。該產品代號傳為 B790，先前報導指出最快可能九月與新一代 iPhone 一同亮相。',
         vocab=[('release candidate', '軟體術語「候選發布版」，縮寫 RC，指接近正式版的測試版本。'),
                ('buried (adj.)', '「被埋藏的」，此處指藏在檔案深處未公開的內容。'),
                ('obstruct (v.)', '「阻擋、遮蔽」，名詞 obstruction。')]),
    dict(title_en='Google Reveals the Desktop Camera App',
         title_zh='Google 公開 Desktop Camera 應用程式',
         gist_en="Google showed the full Desktop Camera app ahead of the Googlebook launch. Built for tablets, laptops and desktops, it has a responsive large-screen layout, external USB webcam support, ML-powered document scanning with automatic cropping, and QR scanning.",
         body_zh='Google 在 Googlebook 上市前公開了完整的 Desktop Camera 應用程式。這款 App 專為平板、筆電與桌機設計，具備適應大螢幕的響應式介面、支援外接 USB 網路攝影機、以機器學習驅動的文件掃描（含自動裁切與增強），以及 QR code 掃描。整體設計與平板上的 Pixel 相機十分相似，看得出 Google 想在大螢幕裝置上維持一致的拍照操作體驗。',
         vocab=[('responsive (adj.)', '「響應式的」，介面能依螢幕尺寸自動調整版面。'),
                ('crop (v.)', '「裁切（影像）」，automatic cropping 即自動裁切。'),
                ('resemble (v.)', '「與……相似」，及物動詞，後面不加 to。')]),
    dict(title_en='Generative AI Shifts Rather Than Erases UX Value',
         title_zh='生成式 AI 沒有消滅 UX 的價值，只是搬了位置',
         gist_en="Tools like Figma's Make Designs speed up interface creation, but that shifts where design value sits rather than removing it. As AI-generated interfaces converge on the same patterns, advantage comes from deep user research and observed behaviour that AI cannot gather on its own.",
         body_zh='像 Figma 的 Make Designs 這類生成式 AI 工具，確實加快了介面產出速度，但這只是讓 UX/UI 設計的價值「換了位置」，而不是消失。當 AI 生出來的介面越來越趨同於同一套模式，真正的競爭優勢就會回到「深度使用者研究」與「實地觀察到的行為」上，而這些是 AI 沒辦法自己蒐集的。新手設計師則面臨新難題：太依賴 AI 現成答案，會跳過培養專業判斷所需的實作歷練。',
         vocab=[('converge on X', '片語「收斂到 X、趨同於 X」，反義 diverge。'),
                ('erase (v.)', '「抹除」，此處與 shift（位移）形成對比。'),
                ('hands-on (adj.)', '「親自動手的」，hands-on learning 指實作中學習。')]),
    dict(title_en='Accessibility Keeps Getting Dropped in Handoffs',
         title_zh='無障礙設計，總是在交接時被弄丟',
         gist_en="An accessible design can still ship as an inaccessible product, because early approval only proves a concept could be built accessibly. Missing alt text and broken keyboard focus come not from ignorance but from accessibility having no owner during handoffs between design, development and QA.",
         body_zh='就算設計稿本身是無障礙的，最後仍可能做出不無障礙的產品，因為早期核可只證明「這個概念有可能做到無障礙」，不代表它真的會被做到。缺少替代文字、鍵盤焦點壞掉這類問題，往往不是開發者不懂，而是在設計、開發、測試之間交接時，無障礙這件事沒有明確的負責人。解法是把無障礙需求寫成可測試的驗收條件、每個階段指定負責人，並提早設檢查點，而不是只靠最後一次稽核。',
         vocab=[('accessible (adj.)', '「無障礙的、可及的」，名詞 accessibility，常縮寫 a11y。'),
                ('ownership (n.)', '「權責歸屬」，have no owner 指沒有人負責。'),
                ('testable criteria', '「可測試的驗收標準」，criteria 為 criterion 的複數。')]),
    dict(title_en='Designing a Brand System for Three Billion People',
         title_zh='替三十億人設計一套品牌系統',
         gist_en="Instagram's first major brand refresh in ten years came from thousands of small deliberate decisions rather than one bold move. The team built a flexible system that can evolve, accepted that change always draws criticism, and believes the best work is crafted so carefully that it ends up feeling effortless.",
         body_zh='Instagram 十年來首次大規模品牌翻新，靠的不是單一大膽決策，而是數千個刻意為之的小決定。面對全球數十億使用者，這個專案投入大量協作、研究、回饋與測試，讓品牌識別在現代化的同時，保住創意、連結與自我表達等核心價值。團隊刻意打造一套能隨時間演進的彈性系統，也接受改版必然招來批評，並相信最好的設計是「精雕細琢到最後看起來毫不費力」。',
         vocab=[('refresh (n.)', '此處為名詞「改版、翻新」，brand refresh 指品牌識別更新。'),
                ('deliberate (adj.)', '「刻意的、深思熟慮的」，注意與 deliberately（副詞）搭配使用。'),
                ('effortless (adj.)', '「毫不費力的」，effort＋-less，此處為稱讚語。')]),
    dict(title_en='AI Video and Image Generation Tools',
         title_zh='AI 影音與圖像生成工具',
         gist_en="Two listings cover browser-based generators that turn prompts into videos, images and social content, with editing available at each stage so the user keeps creative control.",
         body_zh='本期收錄兩則同類型的網站工具，都是把文字提示轉換成影片、圖像與社群內容的線上生成服務，並強調在每個階段都能編輯調整，讓使用者保有完整的創作主導權。',
         vocab=[('prompt (n.)', '「提示詞」，AI 生成領域的核心名詞。'),
                ('refine (v.)', '「細修、精煉」，比 edit 更強調反覆打磨。'),
                ('at every stage', '片語「在每個階段」，stage 指流程中的環節。')]),
    dict(title_en='The Evening Shift',
         title_zh='夜班：一位資深設計師重新找回熱情',
         gist_en="After years drained by meetings and documentation, a veteran designer rediscovered the craft by building products directly with AI-assisted tools. A side project that reached the App Store in six weeks convinced him that shipping real software beats producing handoffs and specifications.",
         body_zh='在被會議、文件與設計流程消耗多年之後，資深設計師 Jamie Rothwell 靠著用 AI 輔助工具直接動手做產品，重新找回對這門手藝的熱情。一個從發想到上架 App Store 只花六週的副業專案，讓他體會到「真的把軟體做出來」遠勝過產出一堆交接文件與規格書。被裁員之後，他更全力投入這種「設計師兼建造者」的路線，主張適應力與貼近產品比守護傳統設計流程更重要，並認為很多設計師其實早在 AI 出現之前，就已經被流程磨掉了工作的樂趣。',
         vocab=[('drained (adj.)', '「被榨乾的、精疲力盡的」，動詞 drain 原意為排水。'),
                ('veteran (n./adj.)', '「資深老手（的）」，不限於軍事用途。'),
                ('side project', '「副業專案」，指本職之外自行開發的作品。')]),
    dict(title_en='xAI Imagine Image 2.0 Lands Just Behind GPT-Image-2',
         title_zh='xAI Imagine Image 2.0 緊追 GPT-Image-2',
         gist_en="xAI released Imagine Image 2.0 as a Quality Mode on its web and mobile apps, with API access planned. On one leaderboard its faster variant placed second globally in both image editing and text-to-image, trailing OpenAI's GPT-Image-2.",
         body_zh='xAI 推出 Imagine Image 2.0，以「品質模式」形式登上 grok.com/imagine 與 Grok 行動應用，API 存取則在規劃中。在 2026 年 8 月 7 日的 Arena 排行榜上，其速度較快的 low 版本在影像編輯與文生圖兩個類別都拿下全球第二，僅次於 OpenAI 的 GPT-Image-2。這次更新還帶來魔術棒、影像分割、去背、多參考圖編輯與智慧縮放等工具，以及預設範本與角色場景一致性功能。',
         vocab=[('trail (v.)', '「落後於」，動詞用法，trailing X 指名次或表現在 X 之後。'),
                ('variant (n.)', '「變體、版本」，指同一產品的不同規格。'),
                ('leaderboard (n.)', '「排行榜」，AI 領域常用來比較模型表現。')]),
    dict(title_en='A Hand-Drawn Poster Goes Viral',
         title_zh='手繪電影海報意外爆紅',
         gist_en="When official posters failed to arrive because of shipping problems, a Canadian cinema drew its own by hand. The hand-lettered design went viral, with fans praising its personality over the official artwork.",
         body_zh='加拿大 Prince George 一家 Cineplex 影城因為運送問題收不到官方海報，乾脆由員工自己手繪了一張《蜘蛛人：全新一天》的海報。這張手寫字體、還讓蜘蛛人比出搖滾手勢的設計在社群上爆紅，許多影迷認為它比官方美術更有個性，也反映出大眾對電影美術原創性的渴望。',
         vocab=[('go viral', '片語「爆紅、瘋傳」，viral 源自 virus（病毒）。'),
                ('hand-lettered (adj.)', '「手寫字體的」，letter 當動詞為「書寫字母」。'),
                ('personality (n.)', '此處指作品的「個性、特色」，不只用於形容人。')]),
]))

TOPICS.append(dict(zh='行銷', en='TLDR Marketing', date='2026-08-19', arts=[
    dict(title_en='Platforms Get Weirder to Grow Wider',
         title_zh='平台越玩越怪，只為了長得更寬',
         gist_en="With growth flatlining, social platforms are blurring the line between feeds, streaming and connected TV. One now exports creator videos built on major film IP straight into a streaming app, while another is testing a shoppable home-makeover show packed with QR codes.",
         body_zh='社群平台的成長趨於停滯，於是它們開始模糊「社群動態、串流影音、聯網電視」三者之間的界線，尋找新的觸及來源。TikTok 現在能把以 Pixar、Marvel、Star Wars 等 IP 製作的創作者影片，直接輸出到 Disney+ App 裡，讓娛樂與授權品牌獲得一條版權無虞的漏斗上層通路。Pinterest 則在 Roku 上測試一檔可購物的居家改造節目，塞滿導向可下單看板的 QR code，想把被動看電視轉換成直接成交。',
         vocab=[('flatline (v.)', '「拉平停滯」，原指心電圖成一直線，引申為毫無成長。'),
                ('blur the line', '慣用語「模糊界線」，blur 為使模糊。'),
                ('top-of-funnel', '行銷術語「漏斗上層」，指尚未產生購買意圖的廣泛受眾。')]),
    dict(title_en='Nine Months of AI Overview Traffic Data',
         title_zh='九個月的 AI 摘要流量數據告訴我們什麼',
         gist_en="AI Overviews are becoming a real but highly volatile source of organic traffic, accounting for 7.53% of organic sessions over nine months, with 22.4% of those events misattributed to Direct. Structured content such as pricing and comparison tables was favoured, while stale content lost citation share.",
         body_zh='AI 摘要（AI Overviews）正成為一個實質但極不穩定的自然流量來源。九個月的數據顯示，它佔了 7.53% 的自然造訪，但其中有 22.4% 的事件被錯誤歸因成「直接流量」。Google 明顯偏好具體且結構化的內容，例如價格、交通時間、路線與 HTML 比較表格，而過時內容則會逐漸失去被引用的份額。建議在 GA4 中直接追蹤 #:~:text= 訊號，並依引用資料決定內容更新優先順序。',
         vocab=[('volatile (adj.)', '「波動劇烈的、不穩定的」，金融與數據分析常用。'),
                ('misattribute (v.)', '「錯誤歸因」，mis-（錯誤）＋ attribute（歸因於）。'),
                ('stale (adj.)', '「陳舊過時的」，此處指長期未更新的內容。')]),
    dict(title_en='A Comments-Section Social Strategy That Scales',
         title_zh='把「留言區」做成可複製的社群策略',
         gist_en="A growth team stumbled into a strategy when one comment pulled in over 300,000 likes, then turned it into a deliberate programme of 200 to 350 comments a month. Daily new followers grew roughly a hundredfold, and the rule that makes it work is to only join conversations where the brand has an earned reason to speak.",
         body_zh='BetterHelp 的成長團隊原本是誤打誤撞：一則 TikTok 留言拿下超過 30 萬個讚，於是他們把這件事變成一套刻意執行的計畫。品牌現在每月在 200 到 350 則貼文下留言，其中 10 到 20 則能突破一萬讚，每日新增追蹤數自去年秋天全力投入以來成長約百倍。真正讓它有效的規則很窄：只在「心理健康品牌明顯有立場說話」的話題下留言，而且絕不在留言裡推銷。',
         vocab=[('stumble into X', '片語「無意間撞見／誤打誤撞進入 X」。'),
                ('deliberate (adj.)', '「刻意的」，與 stumble into（偶然）形成對照。'),
                ('earned (adj.)', '「靠實力贏得的」，an earned reason 指站得住腳的正當理由。')]),
    dict(title_en='A Framework for Running Better Marketing Tests',
         title_zh='讓行銷實驗更有價值的排序框架',
         gist_en="Prioritise experiments on commercial opportunity, learning value, evidence strength, addressability and resource cost, then define what decision each possible outcome will trigger before the test starts. Set commercial thresholds alongside statistical ones so a measurable result only leads to action when it is worth implementing.",
         body_zh='用 CLEAR 框架來排序行銷實驗：依商業機會、學習價值、既有證據強度、可觸及性與資源需求評分，並且在測試開始「之前」就先定義好，每一種可能結果會觸發什麼決策。除了統計顯著性，也要同時設定商業成功門檻，這樣才不會出現「數字有差異但不值得投入實作」的情況。最後把已驗證的結論回饋到後續規劃，避免團隊一再重測早就知道答案的問題。',
         vocab=[('threshold (n.)', '「門檻值」，設定判斷是否採取行動的界線。'),
                ('addressability (n.)', '行銷術語「可觸及性」，指能否精準鎖定該受眾。'),
                ('trigger (v.)', '「觸發（某個決策或行動）」。')]),
    dict(title_en='How to Audit LinkedIn Conversion Tracking',
         title_zh='如何稽核 LinkedIn 的轉換追蹤設定',
         gist_en="Do not treat a conversions API as set-and-forget. Audit it across three areas: confirm the CRM consistently captures key funnel events, compare platform data against the CRM to catch missing or misnamed events, and assign a clear owner so stack changes do not silently break tracking.",
         body_zh='不要把 LinkedIn 的 Conversions API 當成「設定完就不用管」。稽核要分三塊：先確認 CRM 有穩定記錄關鍵漏斗事件、欄位與工作流程都是最新的；接著把 LinkedIn 的轉換資料與 CRM 對帳，抓出遺漏、命名錯誤或歸因錯誤的事件；最後指派明確負責人並把設定文件化，避免行銷技術堆疊一有變動就把追蹤弄壞。修正順序建議先補 CRM 缺口，再處理資料對應問題。',
         vocab=[('set-and-forget', '慣用語「設定完就不用再管」，此處為否定用法。'),
                ('funnel (n.)', '行銷術語「漏斗」，描述使用者從認知到成交的階段。'),
                ('map (v.)', '「對應」，data mapping 指欄位之間的對照關係。')]),
    dict(title_en='Reddit Tests Audio and Video Versions of Posts',
         title_zh='Reddit 測試把熱門貼文變成語音與影片',
         gist_en="Reddit is testing audio and video versions of its most popular posts so users can read or play a thread inside the app. The test stays limited to select English-language communities and does not replace the original text or comments.",
         body_zh='Reddit 正在測試把最熱門的貼文轉成語音與影片版本，讓使用者能在 iOS 與 Android App 裡選擇「閱讀」或「播放」一整串討論。目前測試僅限部分英語社群，也不會取代原本的文字與留言。此舉的背景是：創作者早就把爆紅的 Reddit 貼文做成播客風格內容，投放到 TikTok、Reels 與 YouTube Shorts，Reddit 想把這塊體驗收回自家平台。',
         vocab=[('thread (n.)', '論壇術語「討論串」。'),
                ('narrate (v.)', '「旁白、口述」，名詞 narration。'),
                ('in-house (adj./adv.)', '「自家內部的」，bring X in-house 指把外部的事收回自己做。')]),
    dict(title_en='Narrative Debt',
         title_zh='敘事債',
         gist_en="Narrative debt is the tension created when content raises a question, makes a promise or opens a loop. The bigger the promise, the longer people will wait for the payoff, so answer small questions quickly and avoid opening too many loops at once.",
         body_zh='所謂「敘事債」，是內容拋出問題、給出承諾或開啟一個懸念時所製造的張力。承諾越大，觀眾願意等待兌現的時間就越長。小問題應該很快回答，大問題則可以慢慢鋪陳；但要避免同時開太多懸念，否則內容會顯得散亂。訣竅是只留幾個夠強的問題懸著，並在對的時機一一兌現，藉此維持注意力。',
         vocab=[('open a loop', '寫作術語「開啟懸念」，對應 close the loop（收尾兌現）。'),
                ('payoff (n.)', '「回報、兌現」，指鋪陳之後給出的滿足感。'),
                ('scattered (adj.)', '「散亂的、不聚焦的」，動詞 scatter 為散落。')]),
    dict(title_en='B2B Keeps Rediscovering the Star System',
         title_zh='B2B 行銷一再重新發現「明星制度」',
         gist_en="B2B marketers keep rediscovering that people follow people, but this is a fundamental media principle rather than a platform tactic. Mature teams identify the employees worth building an audience around, develop repeatable content formats, and build systems that make both the person and the company more valuable over time.",
         body_zh='B2B 行銷圈一再「重新發現」一件事：人們追隨的是人，不是公司帳號。但這其實是媒體的基本原理，不是某個社群平台上的戰術。以好萊塢明星制度作類比，企業應該圍繞具辨識度的員工去經營受眾，而不是把他們當成單純的發布通道。最成熟的團隊會先挑出值得投資的人選，發展可重複操作的內容形式，並建立讓「個人」與「公司」價值同步累積的機制。',
         vocab=[('rediscover (v.)', '「重新發現」，re-＋discover，此處帶點反諷。'),
                ('tactic (n.)', '「戰術」，與 principle（原理）、strategy（策略）層級不同。'),
                ('repeatable (adj.)', '「可重複執行的」，商業流程設計的重要特性。')]),
    dict(title_en='Where the Better-For-You Aisle Grows Next',
         title_zh='健康飲品的下一步成長在哪裡',
         gist_en="A study of 100 buyers found a serious retention problem, with 35% no longer regularly buying any of the five brands studied. Retention was much stronger when a drink replaced something specific such as soda rather than replacing water or nothing at all.",
         body_zh='一份針對 100 位健康取向飲品消費者的研究發現嚴重的回購問題：有 35% 的人已經不再固定購買研究中的任何一個品牌。關鍵洞察是，當這款飲料是拿來「取代某個具體的東西」時，留存率明顯較高——例如取代汽水的 OLIPOP 留住了 65% 的買家，而「什麼都沒取代」的族群只留住 25%。品牌應聚焦在自己究竟在替換掉什麼習慣，同時解決包裝與通路上的障礙。',
         vocab=[('retention (n.)', '「留存、回購」，商業指標 retention rate（留存率）。'),
                ('replace (v.)', '「取代」，此處為理解全文的關鍵動詞。'),
                ('barrier (n.)', '「障礙」，barrier to purchase 指阻礙購買的因素。')]),
]))
