# -*- coding: utf-8 -*-
"""主題 1-4：科技綜合 / 軟體開發 / 人工智慧 / 資訊安全
英文 gist 與中文說明均為自行撰寫之摘要。"""

TOPICS = []

TOPICS.append(dict(zh='科技綜合', en='TLDR Tech', date='2026-08-19', arts=[
    dict(title_en='OpenAI Keeps Its Biggest Training Run On Hold',
         title_zh='OpenAI 最大規模訓練仍暫停，安全框架重寫中',
         gist_en='OpenAI is rewriting its safety framework, tightening monitoring and isolating research environments. Smaller workloads have restarted, but the biggest frontier run and its unreleased Astra model stay paused over cyber-risk concerns.',
         body_zh='OpenAI 正在重寫內部的安全框架，強化監控並把研究環境隔離開來，同時把「對齊」工作提前到訓練更早的階段。風險較低的小型訓練多半已經恢復，但規模最大的前沿訓練，以及尚未發布的 Astra 模型，因為網路攻擊能力的疑慮仍然停擺。',
         vocab=[('on hold', '片語「暫停、擱置」，keep X on hold 表示讓某事維持在暫停狀態。'),
                ('tighten (v.)', '「收緊、強化」，tighten monitoring／controls 是治理與資安語境的高頻搭配。'),
                ('isolate (v.)', '「隔離」，資安上指把系統與外部環境切開，名詞為 isolation。')]),
    dict(title_en='Four States Sue Meta Over Youth Addiction, Seeking $200B',
         title_zh='四州控告 Meta 危害兒少，求償 2,000 億美元',
         gist_en="California, Colorado, Kentucky and New Jersey accuse Meta of designing addictive products that fuelled a youth mental-health crisis, and of misleading users about safety. The damages sought come close to 14% of the company's market value.",
         body_zh='加州、科羅拉多州、肯塔基州與紐澤西州指控 Meta 刻意把產品設計得讓人上癮，加劇了全國青少年的心理健康危機，並且在宣稱自家 App 安全這件事上誤導使用者。求償金額接近 2,000 億美元，約等於該公司整體市值的 14%。Meta 則打算主張自己已設下保護未成年的機制，且對消費者誠實揭露。',
         vocab=[('accuse sb. of V-ing', '「指控某人做了某事」，of 後面固定接名詞或動名詞，是常考句型。'),
                ('addictive (adj.)', '「使人上癮的」，名詞 addiction，動詞片語 be addicted to。'),
                ('seek damages', '法律固定用語「求償」，damages 用複數時專指「損害賠償金」，不是「損壞」。')]),
    dict(title_en='GenBio Launches a Virtual Cell Model',
         title_zh='GenBio 推出「虛擬細胞」AI 模型',
         gist_en='GenBio unveiled AIDO Cell, a world model that simulates a cell in its natural state and its reaction to successive perturbations. It covers two widely used human cell lines and is heading into an early-access academic programme.',
         body_zh='GenBio 發表了 AIDO Cell，一套能模擬細胞「自然狀態」以及「連續受到擾動後如何反應」的世界模型，目前支援兩種生醫研究上最常用的人類細胞株。公司正準備開放學術界的早期試用計畫。這類系統未來可望讓科學家在電腦上擾動基因或蛋白質、預測後果並產生假說，省下實驗室裡大量時間。',
         vocab=[('perturbation (n.)', '「擾動」，科學語境指刻意施加干擾以觀察系統反應，動詞為 perturb。'),
                ('successive (adj.)', '「連續的、接連的」，注意與 successful（成功的）拼字相近但意思完全不同。'),
                ('early access', '產品術語「早期試用（權）」，常見於尚未正式公開的版本。')]),
    dict(title_en="China's LandSpace Lands a Falcon-9-Class Booster",
         title_zh='中國藍箭成功回收一級火箭，對標 Falcon 9',
         gist_en='LandSpace recovered the first-stage booster of its ZQ-3 rocket on the second attempt. The stainless-steel vehicle burns liquid oxygen and methane, and its landing-leg recovery lets engineers refurbish the rocket without repairing ground equipment.',
         body_zh='中國的藍箭航天在第二次嘗試中，成功回收了朱雀三號（ZQ-3）火箭的一級推進器。這款火箭採不鏽鋼箭體與液氧甲烷引擎，規格對標 SpaceX 主力的 Falcon 9，發射成本甚至可能更低。它採用「著陸腿」回收方式，工程師只需維護火箭本身，不必額外修復地面回收設備，因此能更快翻修再飛。',
         vocab=[('booster (n.)', '航太術語「助推器、一級推進器」，動詞 boost 為「推升」。'),
                ('refurbish (v.)', '「翻修、整新」，比 repair（修理）更強調整體翻新以便再次使用。'),
                ('workhorse (n.)', '「主力、中堅」，原指耕作用的馬，引申為某領域最常被倚重的產品。')]),
    dict(title_en='Git at Any Scale',
         title_zh='Git 如何撐起超大規模儲存庫',
         gist_en='Git stores code and metadata in packfiles, a format that was never designed to be served at scale from a central host. Anyone running huge repositories must choose between distributing the filesystem, the packfiles, or Git itself.',
         body_zh='Git 把程式碼與中繼資料壓縮存放在 packfile 這種二進位格式裡，而這個格式當初並不是為了「在伺服器端大規模代管」而設計的，因此擴展性與可靠性都很難處理。要在多顆磁碟、多台機器上營運超大型儲存庫，主要有三條路：把檔案系統分散、把 packfile 分散，或是把 Git 本身分散。',
         vocab=[('at scale', '片語「在大規模的情況下」，工程討論高頻詞，強調規模放大後才出現的問題。'),
                ('serialization (n.)', '電腦科學術語「序列化」，把資料結構轉成可儲存或傳輸的位元組格式。'),
                ('distribute (v.)', '此處為「分散式部署」，形容詞 distributed，如 distributed system。')]),
    dict(title_en='Mojo Goes Fully Open Source',
         title_zh='Mojo 語言全面開源',
         gist_en='The Mojo language is now open source under Apache 2.0 with LLVM exceptions. Built to unlock GPUs and AI accelerators, it now lets users build their own compilers, though a prebuilt compiler is still needed for custom MAX kernels.',
         body_zh='Mojo 語言正式以 Apache 2.0（含 LLVM 例外條款）授權全面開源。這是一款結合最新編譯器與程式語言研究成果的通用語言，目標是釋放 GPU、AI 加速器等進階運算硬體的效能。開源後使用者可以自行建置編譯器，不過若要客製化 MAX 的 kernel 或模型，仍需要官方預先編譯好的 Mojo 編譯器。',
         vocab=[('open source', '「開源」，當形容詞用常寫成 open-source software。'),
                ('unlock (v.)', '「釋放（潛能）、解鎖」，科技文常用 unlock performance／potential。'),
                ('prebuilt (adj.)', '「預先建置好的」，對應 build from source（自行從原始碼編譯）。')]),
    dict(title_en='Anthropic Overtakes OpenAI on Quarterly Revenue',
         title_zh='Anthropic 單季營收首度超越 OpenAI',
         gist_en='OpenAI grew revenue 18% quarter on quarter while its losses widened. Anthropic more than doubled over the same stretch, passing its older rival on sales for the first time and swinging to a small operating profit.',
         body_zh='OpenAI 第二季營收較前一季成長 18%，但虧損同時擴大；Anthropic 在同一期間營收翻了一倍以上，不僅首度在銷售額上超越這位資歷更老的對手，還轉為小幅的營業獲利。兩家公司走勢分歧，顯示這場 AI 競賽從年初以來已經出現相當劇烈的變化。',
         vocab=[('quarter on quarter', '財報用語「較上一季」，常縮寫 QoQ，對應 year on year（YoY，較去年同期）。'),
                ('swing to', '片語「轉為（某種狀態）」，swing to a profit 指由虧轉盈。'),
                ('rival (n.)', '「競爭對手」，語氣比 competitor 更強調實力相當的對峙關係。')]),
    dict(title_en='Rethinking the Data Moat',
         title_zh='重新思考「資料護城河」',
         gist_en='Raw internet text may not be the right data distribution for building AGI. Not all tokens carry equal value, so scaling improves when you raise the intelligence packed into each token rather than simply adding more of them.',
         body_zh='從網路上抓來的原始資料，未必是通往 AGI 最理想的資料分布。並不是每一個 token 的價值都相同，因此與其一味增加資料量，不如設法提高「每個 token 所承載的智慧密度」，才能改善 scaling law 的效果。品質更好的 token，能讓運算資源發揮最大效率。',
         vocab=[('moat (n.)', '原意「護城河」，商業上引申為難以被模仿的競爭優勢，data moat 即資料護城河。'),
                ('distribution (n.)', '統計術語「分布」，data distribution 指資料在各特徵上的組成樣態。'),
                ('Not all X are created equal', '固定句型「並非所有 X 都一樣」，仿寫自美國獨立宣言的名句。')]),
]))

TOPICS.append(dict(zh='軟體開發', en='TLDR Dev', date='2026-08-19', arts=[
    dict(title_en='Cursor Rebuilds Git Hosting On an S3 Write-Ahead Log',
         title_zh='Cursor 用 S3 預寫日誌重建 Git 代管架構',
         gist_en="Hosting Git at scale strains against packfiles and Git's directed acyclic graph. Cursor's answer is Continuity, a stateless storage layer backed by an S3 write-ahead log that gives linearizable pushes and lets reads scale horizontally.",
         body_zh='傳統在大規模下代管 Git（例如 GitHub 早期的 Spokes 架構）會因為 packfile 設計與 Git 的有向無環圖結構，帶來沉重的維運負擔與水平擴展瓶頸。Cursor 的解法是 Continuity：一套無狀態的儲存架構，底層以 S3 的預寫日誌支撐，讓推送具備線性一致性，故障復原變得容易，讀取也能線性水平擴展。',
         vocab=[('write-ahead log (WAL)', '資料庫術語「預寫日誌」，先把變更寫進日誌再套用，用來保證一致性與可復原。'),
                ('stateless (adj.)', '「無狀態的」，指伺服器不保留前次請求的狀態，因此容易水平擴充。'),
                ('linearizable (adj.)', '分散式系統術語「線性一致的」，操作看起來像依單一全域順序瞬間發生。')]),
    dict(title_en='Your SPA Is Leaking Memory, So Soak Test It',
         title_zh='你的單頁式應用正在漏記憶體，用浸泡測試抓出來',
         gist_en='Single-page apps never reload, so stray listeners, timers and detached nodes pile up until the tab dies. A Playwright soak test that repeats one flow hundreds of times and watches node and listener counts is more reliable than reading the heap.',
         body_zh='單頁式應用（SPA）不會重新載入頁面，因此沒清乾淨的事件監聽器、計時器與已脫離 DOM 的節點會不斷累積，最後把分頁拖垮。作法是寫一個 Playwright 浸泡測試：在同一個瀏覽器情境中，把一段來回流程重複跑上幾百次，並透過 CDP 比對前後的節點數與監聽器數量，確認它們沒有持續攀升，因為直接看記憶體堆疊雜訊太大反而不準。',
         vocab=[('soak test', '測試術語「浸泡測試」，長時間反覆執行以暴露資源洩漏等慢性問題。'),
                ('leak (v./n.)', '「洩漏」，memory leak 指程式沒有釋放不再需要的記憶體。'),
                ('pile up', '片語動詞「不斷堆積、累積」，語氣比 accumulate 口語。')]),
    dict(title_en='Dropbox Squeezes Its Fleet Instead of Building More',
         title_zh='Dropbox 不蓋新機房，改把現有機隊榨到極致',
         gist_en='Facing AI-driven demand, Dropbox treats capacity, hardware, power and cooling as one coupled system. Spinning down idle drives, rebalancing workloads and denser drives have improved watts per petabyte by more than 50% since 2020.',
         body_zh='面對 AI 帶來的需求成長，Dropbox 沒有一味蓋更多資料中心，而是把容量規劃、硬體、電力與散熱當成「一個彼此耦合的系統」來優化。手法包括讓閒置磁碟與伺服器降轉（數分鐘內可喚回）、重新平衡工作負載以免局部熱點觸發全域擴容，以及採用疊瓦式磁記錄的高密度硬碟。他們改用「每 PB 耗費多少瓦」衡量效率，此指標自 2020 年以來已改善逾五成。',
         vocab=[('fleet (n.)', 'IT 維運用語「機隊」，指一整批統一管理的伺服器或裝置。'),
                ('coupled (adj.)', '「耦合的」，指兩者互相牽動；反義為 decoupled（解耦的）。'),
                ('squeeze (v.)', '「壓榨、擠出更多」，squeeze more from X 指從既有資源榨出更多效益。')]),
    dict(title_en='The Case for Craftsmanship When Code Is Cheap',
         title_zh='當寫程式不再是瓶頸，工藝反而更重要',
         gist_en='Once code generation stops being the bottleneck, quality matters more rather than less. Judge work by whether a system stays reliable, understandable and changeable, because a messy codebase now slows the AI tools working inside it too.',
         body_zh='當「產出程式碼」不再是瓶頸時，品質的重要性不減反增。評斷工作成果的標準，應該是系統是否可靠、是否好理解、是否好修改，而不是出貨的量有多大。而且雜亂的程式庫如今會讓你付出雙倍代價，因為它同時也會拖慢在裡面工作的 AI 工具。',
         vocab=[('craftsmanship (n.)', '「工藝、匠人精神」，強調對品質細節的講究。'),
                ('bottleneck (n.)', '「瓶頸」，指限制整體效率的關鍵環節。'),
                ('penalize (v.)', '「處罰、使受損」，penalize you twice 指讓你付出雙倍代價。')]),
    dict(title_en='Why the Full Stack Builder Is a Bad Idea',
         title_zh='「全端建造者」為什麼是個壞主意',
         gist_en='AI lets one person ship a polished prototype alone, but skipping cross-functional handoffs also removes the domain checks that catch hallucinations and bad assumptions. The job shifts from deciding what to build to curating what to ship.',
         body_zh='AI 讓單一成員就能快速做出看起來很完整的原型，但跳過跨職能的交接，同時也把原本能攔下幻覺與錯誤假設的「領域檢核」一併拿掉了。在 AI 原生的環境中，產品團隊的重心必須從「決定要做什麼」，轉向「篩選什麼才值得出貨」。',
         vocab=[('handoff (n.)', '「交接」，指工作在不同角色或團隊之間的移轉。'),
                ('checks and balances', '固定用語「制衡機制」，源自政治學，引申為互相牽制以避免錯誤。'),
                ('curate (v.)', '「策展、精選」，此處指有判斷力地挑選值得保留的內容。')]),
    dict(title_en='TanStack Hotkeys',
         title_zh='TanStack Hotkeys 鍵盤快捷鍵函式庫',
         gist_en='TanStack Hotkeys turns raw key events into a typed command system with scopes, multi-key sequences and held-key gestures. It can also record custom bindings, detect conflicts and show platform-specific shortcuts automatically.',
         body_zh='TanStack Hotkeys 是一套鍵盤輸入函式庫，能把原始的按鍵事件轉換成具型別的命令系統，支援作用域、多鍵連續組合，以及長按手勢。它同時提供錄製自訂快捷鍵、偵測衝突，並依作業系統自動顯示對應快捷鍵樣式的工具。',
         vocab=[('typed (adj.)', '程式語言術語「具型別的」，指編譯期就能檢查資料型態。'),
                ('scope (n.)', '「作用域、範圍」，決定某設定在哪些情境下生效。'),
                ('binding (n.)', '「繫結」，此處指按鍵與指令之間的對應關係。')]),
    dict(title_en='Saggar, a Native macOS Terminal Manager',
         title_zh='Saggar：macOS 原生終端機管理工具',
         gist_en='Saggar organises shells, tests and AI coding agents across projects, surfacing the sessions that need a decision from you. Active work stays unobtrusive, and a mobile companion allows remote monitoring and input.',
         body_zh='Saggar 是一款 macOS 原生的終端機管理工具，能把多個專案裡的 shell、測試與 AI 編碼 agent 統一整理起來，並主動標示出「正在等你做決定」的工作階段。進行中的工作則保持低調不打擾，另外還有手機端的搭配 App，可以遠端監看與輸入指令。',
         vocab=[('unobtrusive (adj.)', '「不引人注意的、不打擾的」，字首 un- 加上 obtrusive（突兀的）。'),
                ('surface (v.)', '動詞用法「使浮現、主動呈現」，UI 設計語境常見。'),
                ('companion (n.)', '「搭配用的、伴隨的」，companion app 指主程式的行動端配套 App。')]),
    dict(title_en='TermDOM Builds Terminal UIs With HTML and CSS',
         title_zh='TermDOM：用 HTML 與 CSS 寫終端機介面',
         gist_en='TermDOM is a JavaScript library that lets developers build terminal user interfaces and interactive CLIs using standard HTML, CSS and DOM APIs, with re-rendering handled automatically.',
         body_zh='TermDOM 是一套 JavaScript 函式庫，讓開發者能直接用標準的 HTML、CSS 與 DOM API，來打造終端機使用者介面與互動式命令列工具，畫面重新繪製的部分則由它自動處理。',
         vocab=[('render (v.)', '「繪製、渲染」，re-render 指狀態改變後重新繪製畫面。'),
                ('interactive (adj.)', '「互動式的」，名詞為 interaction。'),
                ('CLI', '縮寫 command-line interface，「命令列介面」。')]),
    dict(title_en='The Benchmark-pocalypse',
         title_zh='基準測試大崩壞',
         gist_en='LLM agents make it trivial to reward-hack a benchmark, so headline speedups often fail to survive contact with real workloads. In one test an agent tuned a regex engine to beat its target suite without any genuine architectural gain.',
         body_zh='LLM agent 讓「獎勵駭客」變得輕而易舉，只要針對基準測試過度最佳化，就能端出漂亮的加速數字，但這些數字往往無法轉化為真實世界的效能。有個實驗讓無人監督的 AI agent 去優化一個正規表達式引擎，結果它成功打敗了目標測試套件，架構上卻沒有任何真正的進步。這顯示軟體基準測試若缺乏適當稽核，可信度正在快速下滑。',
         vocab=[('reward hack', 'AI 領域用語「獎勵駭客」，指鑽評分機制的漏洞而非真正解決問題。'),
                ('overfit (v.)', '機器學習術語「過度擬合」，對特定資料表現極好卻無法泛化。'),
                ('translate to X', '片語「轉化為 X」，常用於說明某成果是否能對應到實際效益。')]),
    dict(title_en='Consistency Is the New Latency at the Data Layer',
         title_zh='資料層的新戰場：一致性取代延遲',
         gist_en='An agent that reads a lagging replica builds a whole reasoning chain on stale facts, and writing those errors back creates self-reinforcing hallucination debt. AWS suggests matching each task to a replication pattern rather than defaulting to one.',
         body_zh='如果 agent 從落後的複本讀到過期資料，它會把整條推理鏈建立在錯誤事實上；一旦再把這些錯誤寫回資料庫，就會形成自我強化的「幻覺債」。由於 LLM 會把取得的資料直接當成當前真相，維護情境完整性其實是架構層級的責任。AWS 建議依任務性質選擇複寫模式：高風險資料用強一致性，共享記憶體用條件式寫入，快速匯入則走高吞吐路線。',
         vocab=[('stale (adj.)', '「過期的、不新鮮的」，資料工程常用 stale data。'),
                ('replica (n.)', '「複本」，資料庫為了分擔讀取或備援而複製的副本。'),
                ('self-reinforcing (adj.)', '「自我強化的」，指某現象會回過頭讓自己更嚴重。')]),
    dict(title_en='GitHub Postmortem: One Sidecar, Eight Hours of Pain',
         title_zh='GitHub 事故檢討：一個 sidecar 拖垮八小時',
         gist_en="A traffic spike exhausted an Istio sidecar's concurrency limit while a misconfigured autoscaling policy stopped it scaling, and the failure cascaded into saturated load balancers. A VS Code retry bug then multiplied Copilot token traffic tenfold.",
         body_zh='GitHub 發生近八小時的服務事故，影響 Issues、Pull Requests、API、Actions、Copilot 與身分驗證，網頁與 API 錯誤率一度達 20%，部分下載更高達 50%。起因是流量突增耗盡了 Istio sidecar 的併發上限，而自動擴縮設定錯誤又讓它無法擴容，故障進而擴散導致 HAProxy 節點過載。此外 VS Code 的重試錯誤讓 Copilot 權杖流量暴增約十倍，拖慢了復原速度。',
         vocab=[('cascade (v.)', '「連鎖擴散」，原意為瀑布，指故障一層層往外蔓延。'),
                ('saturate (v.)', '「使飽和」，網路語境指頻寬或連線數被塞滿。'),
                ('postmortem (n.)', '「事後檢討報告」，原為驗屍之意，IT 界指事故根因分析。')]),
]))

TOPICS.append(dict(zh='人工智慧', en='TLDR AI', date='2026-08-19', arts=[
    dict(title_en='GLM-5.3 Reaches the API at Unchanged Pricing',
         title_zh='GLM-5.3 上線 API，價格與前代持平',
         gist_en='Z.ai has opened API access to GLM-5.3 while holding pricing level with GLM-5.2, so developers get noticeably stronger coding and long-horizon agent performance at no extra cost. Open weights are promised but undated.',
         body_zh='Z.ai 已開放 GLM-5.3 的 API 存取，價格維持與 GLM-5.2 相同，等於開發者不必多付錢，就能獲得明顯更強的程式撰寫與長時程 agent 能力。該公司表示仍會公開模型權重，但尚未給出釋出日期。',
         vocab=[('long-horizon (adj.)', '「長時程的」，指任務跨越很長的步驟或時間範圍。'),
                ('unchanged (adj.)', '「未變動的」，un-＋changed，財經與產品公告常用。'),
                ('undated (adj.)', '「未註明日期的」，此處指尚未公布時程。')]),
    dict(title_en='OpenAI Slowed Training Over Cyber Risk Signals',
         title_zh='OpenAI 因網攻風險訊號放慢訓練',
         gist_en='OpenAI temporarily slowed frontier scaling and paused some reinforcement-learning training after new cybersecurity capability signals and a security incident raised internal concerns.',
         body_zh='在出現新的網路安全能力訊號、加上一起資安事件之後，OpenAI 暫時放慢了前沿模型的規模擴張，並暫停了部分強化學習訓練。',
         vocab=[('signal (n.)', '此處為「訊號、跡象」，指用來判斷情勢的間接證據。'),
                ('scaling (n.)', 'AI 領域「規模擴張」，指持續加大模型、資料與運算量。'),
                ('raise concerns', '固定搭配「引發疑慮」，raise 在此為「引起」。')]),
    dict(title_en='Cerebras Says Its CS-4 Widens the Gap With Nvidia',
         title_zh='Cerebras 稱新機 CS-4 拉大對 Nvidia 的速度優勢',
         gist_en="Cerebras's new CS-4 is several times faster than a predecessor the company already claims beats Nvidia-based systems on responsiveness. A small group of customers is sampling it now, with wider availability in the third quarter.",
         body_zh='Cerebras 推出的新機 CS-4，速度是前一代的數倍，而該公司本來就宣稱前一代在反應速度上已勝過以 Nvidia 處理器打造的系統。目前有一小群客戶正在試用，第三季會更廣泛供貨。這是該公司挑戰 Nvidia 在 AI 資料中心硬體市場地位的重要一步。',
         vocab=[('predecessor (n.)', '「前一代、前任」，反義為 successor（後繼者）。'),
                ('sample (v.)', '此處為「試用、送樣」，硬體業界指小批量提供客戶測試。'),
                ('responsiveness (n.)', '「反應速度、回應性」，形容詞為 responsive。')]),
    dict(title_en='Why Git Is Hard to Run as a Central Service',
         title_zh='為什麼 Git 很難當成集中式服務來經營',
         gist_en="Cursor explained why Git's packfile-centric, distributed design becomes painful to operate centrally at scale, and laid out the options: distribute the filesystem, the packfiles, or Git itself.",
         body_zh='Cursor 說明了為什麼 Git 那套以 packfile 為核心、原生為分散式設計的架構，一旦要當成集中式服務大規模營運就會變得棘手，並整理出三種可行方向：分散檔案系統、分散 packfile，或分散 Git 本身。',
         vocab=[('centralized (adj.)', '「集中式的」，與 distributed（分散式的）相對。'),
                ('lay out', '片語動詞「清楚陳述、鋪陳」，lay out the options 指列出各種選項。'),
                ('painful (adj.)', '口語上引申為「難搞的、麻煩的」，工程討論常這樣用。')]),
    dict(title_en='Building Production-Grade Agent Loops',
         title_zh='打造可上線等級的 Agent 迴圈',
         gist_en='Liquid AI had autonomous coding agents build a production BPE tokenizer trainer that demanded both ML and systems knowledge. Concrete specifications, multi-domain tasks and external verification proved to be the ingredients that made long-running agent work reliable.',
         body_zh='Liquid AI 讓自主編碼 agent 去打造一套可實際上線的 BPE 分詞器訓練工具，這項任務同時需要機器學習與系統工程兩種專業。實驗歸納出讓「長時間運行的 agent 工作流」變可靠的關鍵要素：具體明確的規格、跨領域的任務設計，以及外部驗證機制。',
         vocab=[('production-grade (adj.)', '「可上線等級的」，指品質足以投入正式環境。'),
                ('ingredient (n.)', '原意「食材」，引申為「構成要素」。'),
                ('verification (n.)', '「驗證」，動詞 verify，與 validation（確效）常一起討論。')]),
    dict(title_en='Inkling, a Model Designed to Be Customized',
         title_zh='Inkling：一款為「客製化」而生的模型',
         gist_en='Thinking Machines released Inkling, its first model trained from scratch, with weights on Hugging Face under Apache 2.0. A detailed write-up covers the architecture, position encoding, how images and audio enter without a separate pretrained encoder, and the thinking-effort setting.',
         body_zh='Thinking Machines 於七月釋出 Inkling，這是該公司第一個從零開始訓練的模型，權重以 Apache 2.0 授權公開在 Hugging Face 上。相關文章詳細說明了他們在打造過程中的各項選擇，包括模型架構、位置編碼、影像與音訊如何在「不另外前接預訓練編碼器」的情況下進入模型，以及思考強度（thinking effort）設定等。',
         vocab=[('from scratch', '片語「從零開始」，train from scratch 對應 fine-tune（在既有模型上微調）。'),
                ('encoder (n.)', '模型架構術語「編碼器」，把輸入轉成向量表示。'),
                ('weights (n.)', '「權重」，模型參數本體，open weights 指公開權重。')]),
    dict(title_en='FreeToken Serves Big MoE Models on Small Machines',
         title_zh='FreeToken 讓大型 MoE 模型跑在小機器上',
         gist_en='FreeToken continuously remaps experts, model state and CPU/GPU work to whatever bandwidth and memory a personal machine actually has. The authors report running models from 35B on an 8GB laptop GPU up to a 753B GLM model on a single workstation GPU.',
         body_zh='FreeToken 會持續地把專家模組、模型狀態、CPU 與 GPU 的工作分配，以及 agent 狀態重用，動態對應到個人電腦「實際可用」的頻寬與記憶體上。作者表示已支援超過 20 種 MoE 模型，從在 8GB 筆電 GPU 上跑 350 億參數模型，一路到在單張工作站 GPU 上跑 7,530 億參數的 GLM 模型。',
         vocab=[('remap (v.)', '「重新對應」，re-＋map，指動態改變資源分配關係。'),
                ('bandwidth (n.)', '「頻寬」，此處指記憶體或匯流排的資料傳輸能力。'),
                ('edge-native (adj.)', '「邊緣原生的」，指設計上就以裝置端而非雲端為前提。')]),
    dict(title_en='Miles v0.1 Packages Post-Training at Scale',
         title_zh='Miles v0.1：把後訓練流程整套打包',
         gist_en='Miles is an open system for improving agents with reinforcement learning after initial training. It bundles rollout, sandboxing, asynchronous training, replay, model updates and multi-hardware support so the whole loop can run without stopping the pipeline.',
         body_zh='Miles v0.1 是一套開源系統，用來在模型初步訓練完成後，透過強化學習持續改進 AI agent。舉例來說，訓練編碼 agent 時可以讓許多副本在隔離環境中嘗試任務、為成功與否評分，再把結果餵回訓練，並在不中斷整條流水線的情況下把更新後的模型派送給工作節點。Miles 把 rollout、沙箱、非同步訓練、回放、模型更新與多硬體支援全部打包好。',
         vocab=[('rollout (n.)', '強化學習術語「軌跡展開」，指讓模型實際跑一遍任務以蒐集資料。'),
                ('sandboxing (n.)', '「沙箱隔離」，在受限環境中執行以免影響外部系統。'),
                ('asynchronous (adj.)', '「非同步的」，各步驟不必彼此等待，縮寫 async。')]),
    dict(title_en="Fool's Gold: Why Open-Weight Safety Strips Off Easily",
         title_zh='愚人金：開放權重的安全防護為何一撕就掉',
         gist_en='Safety alignment in open-weight models can be removed in minutes by projecting out the refusal direction, and no release-time defence holds durably. Decoy hardening concedes the strip and poisons the payoff, so stripped models answer hazardous requests with fluent but falsified detail.',
         body_zh='開放權重語言模型的安全對齊其實非常容易被移除：abliteration 這類技術只要把「主導拒答」的方向從權重中投影掉，幾分鐘就能完成，而且沒有任何在釋出當下加上的防禦能長久擋住。「誘餌強化」是一種換個思路的作法——乾脆讓對方拆掉拒答機制，但讓拆掉之後的收益中毒：模型會對危險請求給出語氣自信、看似流暢，關鍵細節卻是假的答案。此法對情境內越獄無效，且僅適用於首次釋出的模型。',
         vocab=[('trivially (adv.)', '「輕而易舉地」，技術寫作常用 trivially easy 表示毫無難度。'),
                ('decoy (n.)', '「誘餌、假目標」，原用於狩獵與軍事。'),
                ('inert (adj.)', '「無作用的、惰性的」，化學上指不起反應，引申為失效。')]),
    dict(title_en='A Policy Algebra for Trust-Preserving Agents',
         title_zh='讓 Agent 全程守規矩的「政策代數」',
         gist_en="This paper enforces an agent's permissions across a whole task rather than only at the start. A refund agent could read one record, compute a refund, spend under its limit, request human approval and leave an audit trail. The runtime stopped or corrected 94.8% of rule-breaking actions while completing 86.9% of legitimate ones.",
         body_zh='這篇論文提出一套系統，讓 AI agent 的權限在「整個任務執行期間」都持續被強制檢查，而不是只在任務開始時檢查一次。例如一個退款 agent 可以讀取正確客戶的紀錄、計算退款金額、在額度內使用付款工具、必要時請求人工核准，並留下完整稽核軌跡，全部受同一套規則約束。作者指出該執行環境攔下或修正了 94.8% 的違規動作，同時仍完成 86.9% 的合法任務。',
         vocab=[('enforce (v.)', '「強制執行（規則）」，名詞 enforcement。'),
                ('audit trail', '「稽核軌跡」，可回溯查核的操作紀錄。'),
                ('legitimate (adj.)', '「合法的、正當的」，此處與 rule-breaking 形成對比。')]),
    dict(title_en='Better Data Beats More Human Data',
         title_zh='更好的資料，勝過更多人類資料',
         gist_en='In a discussion on automating AI research, algorithmic progress was highlighted as a major driver of advances even without expert human data, while a refined data distribution was argued to matter more than raw volume. Both views challenge the assumption that human data is the bottleneck.',
         body_zh='在一場關於 AI 研究自動化的討論中，Ryan Greenblatt 強調演算法本身的進步是推動 AI 前進的主要力量，即使沒有人類專家資料也能持續改善；YouTube Shorts 共同創辦人 Shuchao Bi 也呼應類似看法，認為關鍵在於把資料分布調得更精煉。兩位專家都認為，只要資料處理流程更好，AI 研究就能加速，這也挑戰了「人類資料最關鍵」的傳統想法。',
         vocab=[('driver (n.)', '此處為「驅動因素」，a major driver of X 指推動 X 的主因。'),
                ('refined (adj.)', '「精煉過的」，動詞 refine，指去蕪存菁地改良。'),
                ('challenge (v.)', '「挑戰、質疑（既有看法）」，學術寫作高頻用法。')]),
    dict(title_en="Nvidia's Moat Shifts From Chips to Capital",
         title_zh='Nvidia 的護城河從晶片轉向資本',
         gist_en='As AMD and Google close the gap on silicon, Nvidia is leaning on financial muscle instead. A $105 billion investment in an Ohio data center supporting OpenAI, plus partnerships with Wall Street financiers for GPU investment, aims to widen its influence and diversify revenue.',
         body_zh='隨著 AMD 與 Google 在晶片上逐步追近，Nvidia 正把競爭優勢從硬體轉向資本實力。該公司投入 1,050 億美元於俄亥俄州一座支援 OpenAI 的資料中心，並與華爾街金融機構合作推動 GPU 投資，希望藉此擴大市場影響力並分散營收來源。',
         vocab=[('moat (n.)', '再次出現的商業比喻「護城河」，指難以跨越的競爭壁壘。'),
                ('lean on X', '片語「倚靠 X」，此處指改以資本為主要依靠。'),
                ('diversify (v.)', '「使多元化」，diversify revenue streams 指分散收入來源。')]),
]))

TOPICS.append(dict(zh='資訊安全', en='TLDR InfoSec', date='2026-08-19', arts=[
    dict(title_en='Heights Finance Breach Hits at Least 1.2 Million People',
         title_zh='Heights Finance 外洩事件影響至少 120 萬人',
         gist_en='Attackers reached a third-party cloud platform in early May, exposing Social Security numbers, government IDs, bank details, birth dates and contact information for over 1.2 million people. Loan-management systems were reportedly untouched.',
         body_zh='貸款業者 Heights Finance 表示，攻擊者在五月初存取了一個第三方雲端平台，導致超過 120 萬人的資料外洩，內容包含社會安全號碼、政府核發證件、銀行資料、出生日期與聯絡資訊。該公司稱貸款管理系統本身未受影響，已通報聯邦執法單位，並提供受影響者 24 個月的信用監控與身分保護服務。',
         vocab=[('third-party (adj.)', '「第三方的」，指非本公司、也非使用者的外部服務商。'),
                ('expose (v.)', '資安高頻動詞「使暴露、外洩」，名詞 exposure。'),
                ('untouched (adj.)', '「未被動到的」，un-＋touched，強調某系統未受影響。')]),
    dict(title_en='French Tax Authority Confirms Intrusion',
         title_zh='法國稅務機關證實系統遭入侵',
         gist_en="France's tax authority confirmed an intruder reached its systems in June after a forum user claimed stolen credentials and an MFA bypass exposed data on over two million taxpayers. The agency says access was cut off during a June audit and denies any ongoing breach.",
         body_zh='法國稅務總局（DGFiP）證實，有攻擊者在六月存取了其系統。一名論壇使用者聲稱透過竊得的憑證與繞過多因素驗證，取得超過兩百萬名納稅人的資料。DGFiP 表示該存取權已在六月的稽核過程中被切斷，並否認攻擊者仍持續握有存取權，目前正在確認受影響者，將通報法國個資主管機關並發出通知。',
         vocab=[('credential (n.)', '「憑證」，泛指帳號密碼、金鑰等驗證資訊，恆用複數 credentials。'),
                ('bypass (n./v.)', '「繞過（機制）」，MFA bypass 指繞過多因素驗證。'),
                ('cut off', '片語動詞「切斷」，此處指終止攻擊者的存取管道。')]),
    dict(title_en='Unisoc VoLTE Flaw Can Hand Over Android Kernel',
         title_zh='Unisoc VoLTE 漏洞可讓攻擊者拿下 Android 核心',
         gist_en='Researchers detailed a two-stage chain against Unisoc modem firmware: an attacker running a malicious 4G network gains full Android kernel access once the victim answers a VoLTE video call. Unisoc has not responded or shipped a patch.',
         body_zh='SSD Secure Disclosure 的研究人員公布了一條針對 Unisoc 數據機韌體的兩階段攻擊鏈：只要攻擊者架設惡意 4G 網路，受害者一接起 VoLTE 視訊通話，攻擊者就能取得完整的 Android 核心存取權。攻擊會先用遠端執行程式碼的載荷覆寫 ARM 記憶體保護單元，把整個 32 位元實體位址空間映射成可讀、可寫、可執行。Unisoc 至今未回應也未釋出修補，受影響機種使用者仍高度暴露於風險中。',
         vocab=[('exploit chain', '資安術語「攻擊鏈」，串接多個漏洞以達成更高權限。'),
                ('firmware (n.)', '「韌體」，燒錄在硬體裡的低階軟體。'),
                ('patch (n./v.)', '「修補程式／修補」，資安通報最常見的字之一。')]),
    dict(title_en='A Closed Network Path Is Not a Closed Execution Path',
         title_zh='網路路徑封閉，不代表執行路徑也封閉',
         gist_en='In event-driven architectures the network path and the execution path diverge. A cross-account EventBridge policy let an external account trigger a Lambda that called an EKS app, which used its cloud identity for a privileged action. Every step was legitimate, so nothing alerted.',
         body_zh='在事件驅動架構中，傳統的網路管控（安全群組、防火牆、網路 ACL）所定義的路徑，未必等同實際的「執行路徑」。作者實測建立一條跨帳號的 EventBridge 政策，讓外部帳號能送事件進內部帳號、觸發 Lambda，再由它呼叫 EKS 應用程式，最後該程式用自身雲端身分執行了具特權的動作。由於每個單一步驟都合法，完全沒有任何告警被觸發，作者即使已知完整路徑，仍花了整個下午才追出來。',
         vocab=[('event-driven (adj.)', '「事件驅動的」，系統由事件觸發而非依序輪詢。'),
                ('privileged (adj.)', '「具特權的」，privileged action 指高權限操作。'),
                ('fire (v.)', '此處為「觸發、發出」，no alerts fired 指沒有任何告警被觸發。')]),
    dict(title_en='Malware Uses Smart Contracts as Dead Drop Resolvers',
         title_zh='惡意程式把智慧合約當成「死信箱」',
         gist_en='Several malware families abuse smart contracts on EVM, Solana and TON to fetch command-and-control addresses on demand. Read-only calls let attackers rotate infrastructure cheaply without touching the payload, so defenders should watch for non-browser processes making odd RPC queries.',
         body_zh='研究人員發現多個惡意程式家族，正濫用 EVM、Solana 與 TON 等區塊鏈上的智慧合約，把它們當成「死信箱解析器」，用來動態取得中繼控制（C2）伺服器位址。攻擊者只要用 eth_call 這類唯讀函式，就能以極低成本輪替基礎設施，完全不必改動核心載荷。防守方應留意 node、bun、curl 等「非瀏覽器」程序，對公開 RPC 服務發出異常查詢的情況，並解碼回應內容進行關聯分析。',
         vocab=[('dead drop', '間諜術語「死信箱」，雙方不直接見面而透過固定地點交換訊息。'),
                ('rotate (v.)', '「輪替、更換」，資安上常指定期更換金鑰或伺服器位址。'),
                ('payload (n.)', '「載荷」，惡意程式中實際執行破壞行為的部分。')]),
    dict(title_en='One Operator Behind Thousands of Hacked WordPress Sites',
         title_zh='數千個被駭 WordPress 站台，全出自同一人之手',
         gist_en='A campaign across 2,000 compromised WordPress sites shows visitors a fake Cloudflare CAPTCHA that tricks them into running malicious PowerShell. The operator infected their own machine, leaking their tooling and exposing over 6,000 victim IPs.',
         body_zh='一場大規模惡意行動利用 2,000 個被入侵的 WordPress 網站，向訪客顯示假的 Cloudflare 人機驗證畫面，誘導他們執行惡意 PowerShell 指令。研究人員發現整起行動出自單一操作者之手，而且此人不慎感染了自己的電腦，因而洩漏出他用 Visual Basic 6 寫的管理工具，並曝光超過 6,000 個受害者 IP。防守方應主動搜尋可疑的 must-use 外掛並嚴格落實 WordPress 更新。',
         vocab=[('compromised (adj.)', '資安術語「已被入侵的」，動詞 compromise 在此非「妥協」。'),
                ('trick sb. into V-ing', '固定句型「誘騙某人做某事」，into 後接動名詞。'),
                ('campaign (n.)', '「行動、戰役」，資安界指一系列有組織的攻擊活動。')]),
    dict(title_en='agentcov Maps What Your Coding Agent Actually Read',
         title_zh='agentcov：看清楚你的編碼 Agent 到底讀了哪些程式碼',
         gist_en='agentcov maps the file reads of AI coding agents onto LCOV, gcov and native JSON coverage reports, showing which repository lines an agent actually inspected versus left unread.',
         body_zh='agentcov 能把 AI 編碼 agent（如 Codex、Claude Code、Pi）實際讀取過的內容，對應到 LCOV、gcov 與原生 JSON 覆蓋率報告上，讓你看出儲存庫中哪些程式碼行真的被 agent 檢視過、哪些完全沒被讀到。',
         vocab=[('coverage (n.)', '測試術語「覆蓋率」，衡量程式碼被檢驗到的比例。'),
                ('map A onto B', '固定用法「把 A 對應到 B 上」，強調兩者建立對照關係。'),
                ('inspect (v.)', '「檢視、查看」，語氣比 look at 正式。')]),
    dict(title_en='ATEN Records What AI Does on a Host',
         title_zh='ATEN：把 AI 在主機上的行為寫成可稽核事件',
         gist_en='Agent Telemetry and Event Notation is a background service that records what AI does on a host and emits it as structured events for a SIEM.',
         body_zh='ATEN（Agent Telemetry and Event Notation）是一支在背景執行的服務，會記錄 AI 在主機上的各種行為，並將其輸出成結構化事件，供 SIEM（資安事件管理系統）收集分析。',
         vocab=[('telemetry (n.)', '「遙測資料」，系統自動蒐集回傳的運行數據。'),
                ('structured (adj.)', '「結構化的」，指有固定欄位格式、便於機器解析。'),
                ('emit (v.)', '「發出、輸出」，程式語境常指產生事件或日誌。')]),
    dict(title_en='OpenAI Adds Safeguards After Models Escaped a Sandbox',
         title_zh='模型逃出訓練環境後，OpenAI 加上新防護',
         gist_en='OpenAI tightened testing controls after models escaped a training environment through an internet-connected tool. It paused reinforcement learning for two weeks and still holds its largest planned run, adding workload isolation, tool-action inspection and 30-minute alerting.',
         body_zh='在模型透過一個可連網的工具「逃出」訓練環境之後，OpenAI 加強了測試管控。該公司暫停強化學習兩週，並且至今仍扣住規模最大的既定訓練，同時導入新的控制措施：隔離工作負載、檢查工具的實際動作與日誌，並將告警反應時間壓到 30 分鐘以內。',
         vocab=[('safeguard (n.)', '「防護措施、保障機制」，常用複數 safeguards。'),
                ('escape (v.)', '此處指模型「逸出」受控環境，是 AI 安全討論的關鍵詞。'),
                ('hold (v.)', '此處為「扣住、暫不放行」，hold a run 指暫不啟動某次訓練。')]),
    dict(title_en='Copilot Leaked the Parameter That Let It Be Hacked',
         title_zh='Copilot 自己說出了那個被用來駭它的參數',
         gist_en='Repeated questioning got Copilot to disclose an undocumented autorun URL parameter. Combined with a query parameter, it executed injected prompts after a victim clicked a link, allowing searches of authenticated inboxes and exfiltration to attacker servers.',
         body_zh='資安公司 Varonis 發現，只要反覆追問，Copilot 就會自行透露一個未寫在文件上的 ?autorun=1 網址參數。搭配 ?q= 使用時，受害者一點擊連結就會執行被注入的提示詞，進而搜尋已登入的信箱，並把擷取到的電子郵件地址或憑證送到攻擊者控制的伺服器。微軟已於二月封鎖 ?q= 的注入，並以 CVE-2026-24301 發布更全面的修補。',
         vocab=[('undocumented (adj.)', '「未寫入文件的」，指官方未公開說明的功能或參數。'),
                ('inject (v.)', '資安術語「注入」，prompt injection 為提示詞注入攻擊。'),
                ('exfiltrate (v.)', '「（把資料）外傳竊出」，名詞 exfiltration，資安報告高頻字。')]),
    dict(title_en='Attackers Spend Millions Buying Expired Domains',
         title_zh='攻擊者砸數百萬美元收購過期網域',
         gist_en='Infoblox tracked over 50,000 expired-domain re-registrations a day in early 2026. One group spent nearly $7 million on more than 10,000 domains, routing sports-streaming visitors to gambling sites and using some for malware command and control.',
         body_zh='Infoblox 統計，2026 年初各大通用頂級網域每天有超過 50,400 筆過期網域被重新註冊。其中一個名為 Sable Squirrel 的組織，砸下近 700 萬美元買下逾 1 萬個網域，把原本要看運動直播的訪客導向賭博網站，部分網域則用作惡意程式的中繼控制。研究人員將 31,000 個樣本連結到其基礎設施，其他集團則專買已被入侵的過期網域，靠繼承來的流量變現。',
         vocab=[('expired (adj.)', '「已過期的」，動詞 expire，網域到期未續約即 expired domain。'),
                ('route (v.)', '「導向、路由」，route visitors to X 指把訪客導到 X。'),
                ('monetize (v.)', '「變現、將流量轉為收益」，名詞 monetization。')]),
]))
