# -*- coding: utf-8 -*-
"""主題 10-14：加密貨幣 / 金融科技 / IT 產業 / 資料工程 / 硬體
英文 gist 與中文說明均為自行撰寫之摘要。"""

TOPICS = []

TOPICS.append(dict(zh='加密貨幣', en='TLDR Crypto', date='2026-08-19', arts=[
    dict(title_en='White House Crypto Summit Draws Regulators and Executives',
         title_zh='白宮加密貨幣峰會，監管機關與業者齊聚',
         gist_en="The president attended a White House crypto summit alongside the heads of both the SEC and CFTC, with executives from major exchanges, protocols and venture firms expected. The CFTC is also hosting exchange chief executives at its first Innovation Committee meeting.",
         body_zh='川普親自出席週三的白宮加密貨幣峰會，證管會（SEC）與商品期貨交易委員會（CFTC）兩位首長同行，Coinbase、Ripple、a16z、Chainlink、Paradigm 與 Kalshi 等業者高層預計都會到場。CFTC 也將在週四首度召開創新委員會會議，邀集 Coinbase、Robinhood、Kalshi 與 Polymarket 執行長。這場會議正逢 CLARITY 法案通過機率不高之際。',
         vocab=[('summit (n.)', '「高峰會」，原意為山頂，引申為最高層級的會議。'),
                ('regulator (n.)', '「監管機關」，動詞 regulate，形容詞 regulatory。'),
                ('be expected', '被動語態「預期會（出席）」，新聞寫作常用來表示尚未確認。')]),
    dict(title_en='Citi Plans Bitcoin Custody Launch This Year',
         title_zh='花旗預計今年推出比特幣託管服務',
         gist_en="Citi confirmed its digital asset custody service will launch later this year starting with bitcoin, letting clients hold traditional and crypto assets in one framework. It sits inside a new platform built for continuous trading and shorter settlement cycles.",
         body_zh='花旗確認其數位資產託管服務將於今年稍晚上線，首波支援比特幣，讓客戶能在同一套架構下同時託管傳統資產與加密資產。該服務屬於 Custody+ 平台的一環，這是花旗投資人服務部門為「全天候交易與更短結算週期」打造的新平台，另提供即時資產服務、即時交割、流動性工具與 AI 市場情報。花旗同時也與 ICE 合作代幣化證券，並參與 Swift 的代幣化存款試點。',
         vocab=[('custody (n.)', '金融術語「託管」，代客保管資產，custodian 為託管機構。'),
                ('settlement cycle', '「結算週期」，指交易成立到資產實際交割所需時間。'),
                ('framework (n.)', '此處為「架構、體系」，指統一的管理制度。')]),
    dict(title_en='S&P 500 Perpetuals Go Live on a US Venue',
         title_zh='標普 500 永續合約在美國上線',
         gist_en="Coinbase Derivatives launched a single contract giving US traders perpetual-style exposure to all 500 companies in the S&P 500, the first such product available domestically. It enables leverage on the index and short-term directional bets on the US market.",
         body_zh='Coinbase Derivatives 推出一檔單一合約，讓美國交易者能以「永續合約」形式，一次取得標普 500 全部 500 家公司的曝險，這是美國境內首見的同類產品。它同時支援槓桿操作，讓交易者可對美國股市的短期走勢下重注。',
         vocab=[('perpetual (n./adj.)', '衍生品術語「永續合約」，沒有到期日的期貨合約。'),
                ('exposure (n.)', '金融術語「曝險部位」，指對某資產漲跌的承受程度。'),
                ('leverage (n.)', '「槓桿」，以較少本金操作更大部位，同時放大風險。')]),
    dict(title_en='Stripe Buys OpenRouter to Own AI Micropayments',
         title_zh='Stripe 收購 OpenRouter，搶下 AI 微支付入口',
         gist_en="Stripe agreed to acquire the AI model gateway OpenRouter for over $7 billion, gaining a platform that processes 200 trillion tokens monthly for 10 million users across more than 500 models. Its prepaid credit system handles inference micropayments as deposit balances rather than on-chain settlements.",
         body_zh='Stripe 同意以逾 70 億美元收購 AI 模型閘道 OpenRouter，取得一個每月處理 200 兆個 token、服務 1,000 萬名使用者、串接 500 多個模型與 80 多家供應商的平台。OpenRouter 的預付點數機制，是把 AI 推論的微支付當成「存款餘額」處理，而不是走鏈上結算；USDC 儲值收 5%、刷卡 5.5%，推論價格本身則不加價。這筆交易擴大了 Stripe 既有的區塊鏈布局，與 Bridge、Privy 及 Tempo 的機器支付協定形成一整套。',
         vocab=[('gateway (n.)', '「閘道」，作為系統對外統一入口的中介層。'),
                ('micropayment (n.)', '「微支付」，指金額極小的頻繁交易。'),
                ('markup (n.)', '商業術語「加價、價差」，no markup 指不另外加價。')]),
    dict(title_en='Why AI Agents Need Constrained Wallet Permissions',
         title_zh='為什麼 AI Agent 的錢包權限必須被綁住',
         gist_en="Crypto markets never close and transactions are irreversible, so agents with wallet access need traditional-finance controls rather than one broad permission. Agents reportedly settled only about $73 million on-chain over a year, giving the industry a window to build controls before agent-managed capital scales up.",
         body_zh='加密市場全年無休，而且交易一旦送出就不可逆，因此擁有錢包權限的 AI agent 需要的是傳統金融那一套控管——交易限額、多重簽章核准、硬體安全模組、延遲交割、地址白名單與合約模擬——而不是一組包山包海的權限。據統計，2025 年 5 月到 2026 年 4 月間，AI agent 在鏈上只結算了約 7,300 萬美元，相較同期穩定幣約 46 兆美元的結算規模微不足道。這正好給業界一個在資金規模放大前先把控制機制建好的空窗期。',
         vocab=[('irreversible (adj.)', '「不可逆的」，ir-（否定）＋ reversible，區塊鏈交易的關鍵特性。'),
                ('whitelist (n.)', '「白名單」，僅允許清單內對象通過，反義 blacklist。'),
                ('window (n.)', '此處為「時間空窗、機會之窗」，a window to V 指趁機做某事的時機。')]),
    dict(title_en='How AMMs Could Win the Biggest Markets',
         title_zh='自動造市商如何拿下最大的市場',
         gist_en="The argued structural shift from tokenization is not settlement efficiency but the rise of correlated asset pairs, which strip out the hedging costs built into delta-neutral professional market making. Passive liquidity providers supply the correlated pairs where inventory risk is low, while active ones compete over a few high-volume bridge pairs.",
         body_zh='這篇文章主張，代幣化帶來的主要結構性轉變，並不是結算效率，而是「相關性資產配對」的形成——例如用 NVDA/SPY 取代 NVDA/USD。這種配對消除了專業造市商在 delta 中性策略中內建的避險成本，讓被動的 AMM 策略得以拉近與頂尖造市商之間的績效差距。機制上與現有 DeFi 相同：被動流動性提供者負責存貨風險低的相關配對，主動者則在少數高交易量的橋接配對上競爭。早期數據顯示，十檔代幣化股票在頭十二天就創造 3,300 萬美元交易量。',
         vocab=[('correlated (adj.)', '統計術語「相關的」，名詞 correlation。'),
                ('hedging (n.)', '金融術語「避險」，動詞 hedge，用反向部位抵銷風險。'),
                ('inventory risk', '造市術語「存貨風險」，持有部位期間價格變動的風險。')]),
    dict(title_en='A Dusting Campaign Puts Pressure on Exchanges',
         title_zh='「灰塵攻擊」向交易所施壓',
         gist_en="Small stablecoin transfers are being sent from a sanctioned exchange to addresses that previously interacted with major venues, triggering account freezes until recipients prove they were not dealing with a blacklisted entity. The move is read as pressure on exchanges and regulators to either legitimize the platform or face user backlash.",
         body_zh='孫宇晨旗下、自 5 月 26 日起遭歐盟與英國制裁的 HTX，正把小額 USDT 發送到曾與 Coinbase、Binance、Hyperliquid 互動過的地址，導致 Coinbase 凍結收款者帳戶，直到對方證明自己並非與被列黑名單的實體往來為止。此舉發生在 Binance 準備自 8 月 23 日起限制涉及 HTX 等十餘個平台的出入金之際，被解讀為施壓交易所與歐盟監管機關：要嘛讓 HTX 恢復正當地位，要嘛承受受影響用戶的反彈。',
         vocab=[('dusting (n.)', '加密術語「灰塵攻擊」，發送極小額代幣以標記或騷擾地址。'),
                ('sanction (n./v.)', '「制裁」，注意此字另有「批准」的相反義，需看語境。'),
                ('backlash (n.)', '「強烈反彈」，指群眾對某決策的負面反應。')]),
    dict(title_en='Russia Narrows Retail Crypto Trading to Three Assets',
         title_zh='俄羅斯把散戶加密交易限縮到三種資產',
         gist_en="From September 1 the central bank will restrict retail crypto trading to bitcoin, ether and one approved stablecoin, implementing the country's first regulated trading framework. Non-qualified investors face an annual purchase cap per intermediary, while crypto payments inside the country stay prohibited.",
         body_zh='自 9 月 1 日起，俄羅斯央行將把散戶的加密交易限制在比特幣、以太幣與 USDT 三者，正式啟用該國第一套受監管的交易架構。USDT 是唯一獲准的穩定幣，USDC、DAI 等一律排除在受監管管道之外。非合格投資人每家中介機構每年購買上限為 30 萬盧布（約 3,600 美元），合格投資人則無上限；但由於額度以「每個平台」計算，實際總曝險會隨開戶家數增加。境內以加密貨幣付款仍然違法，明確區隔投資與支付用途。',
         vocab=[('retail (adj.)', '金融語境「散戶的、零售的」，與 institutional（機構的）相對。'),
                ('cap (n.)', '「上限」，動詞亦可，如 cap the amount at X。'),
                ('intermediary (n.)', '「中介機構」，指券商、交易所等居間服務者。')]),
]))

TOPICS.append(dict(zh='金融科技', en='TLDR Fintech', date='2026-08-17', arts=[
    dict(title_en='Stripe Agrees to Acquire OpenRouter',
         title_zh='Stripe 同意收購 OpenRouter',
         gist_en="Stripe reportedly finalized a deal to acquire the AI model gateway OpenRouter for more than $7 billion, months after the startup raised at a $1.3 billion valuation. OpenRouter gives developers one interface onto hundreds of models, making this a bet on owning how businesses route and pay for AI.",
         body_zh='據報導，Stripe 已敲定以逾 70 億美元收購 AI 模型閘道 OpenRouter，距離這家新創以 13 億美元估值募資才過幾個月。OpenRouter 讓開發者透過單一介面存取 400 多個 AI 模型，因此這筆收購等於是 Stripe 押注自己要成為「企業如何路由、管理與支付 AI 用量」的核心基礎設施。',
         vocab=[('finalize (v.)', '「敲定、定案」，名詞 finalization。'),
                ('valuation (n.)', '「估值」，raise at a $X valuation 為募資固定說法。'),
                ('bet on X', '片語「押注在 X 上」，商業語境指策略性賭注。')]),
    dict(title_en='Workday Jumps on Takeover Talk',
         title_zh='傳出收購洽談，Workday 股價跳漲',
         gist_en="Workday shares rose nearly 18% after a report that a private equity firm has been in talks to acquire the enterprise software company, lifting its market value toward $51 billion. The talk lands while investors worry AI could disrupt traditional software business models.",
         body_zh='在媒體報導私募股權公司 Silver Lake 正洽談收購後，企業軟體公司 Workday 股價大漲近 18%，市值攀升至接近 510 億美元。這樁潛在交易出現的時間點，正逢投資人擔憂 AI 可能顛覆傳統軟體商業模式之際，儘管 Workday 近期才把 AI 定位成新的成長來源。',
         vocab=[('takeover (n.)', '「收購、接管」，takeover talks 指收購洽談。'),
                ('lift (v.)', '此處為「推升」，lifting its market value 指帶動市值上升。'),
                ('land (v.)', '此處為「發生、落在（某時間點）」，the news lands while...。')]),
    dict(title_en='Kalshi in Talks to Raise at a $40B Valuation',
         title_zh='Kalshi 洽談以 400 億美元估值募資',
         gist_en="The prediction market is reportedly in advanced talks to raise at least $750 million at a $40 billion valuation, under four months after raising $1 billion at $22 billion. Annualized revenue reportedly hit $4 billion in July, driven largely by sports contracts.",
         body_zh='預測市場平台 Kalshi 據報正與 Sequoia Capital 及 Wellington Management 深入洽談，計畫以 400 億美元估值募得至少 7.5 億美元，距離上一輪以 220 億美元估值募得 10 億美元還不到四個月。該平台七月年化營收據報達 40 億美元，主要由運動賽事合約帶動，同時持續拉開與 Polymarket 的差距，並考慮 2027 年 IPO。',
         vocab=[('advanced talks', '「深入洽談」，advanced 指進入後期階段，非「先進的」。'),
                ('annualized (adj.)', '「年化的」，把短期數字換算成一年的規模。'),
                ('widen a lead', '片語「擴大領先差距」。')]),
    dict(title_en='Nvidia as the World’s Largest Fintech',
         title_zh='把 Nvidia 看成全球最大的金融科技公司',
         gist_en="Nvidia signed memoranda with six of the largest names in global capital to build financing vehicles deploying over $500 billion of third-party money into AI infrastructure. The pitch is that compute is now an investable asset class, priced like real estate or toll roads rather than depreciating hardware.",
         body_zh='Nvidia 與全球資本市場六大機構簽署合作備忘錄，打算建立融資平台（性質接近特殊目的公司 SPV），把超過 5,000 億美元的第三方資金投入 AI 基礎建設。黃仁勳親自上 CNBC，由六家機構高層陪同推銷這個被認為出自他個人的構想。他主張「運算力」如今已是一種可投資的資產類別，其定價邏輯更像不動產或收費公路，而不是會按折舊表逐年報廢的硬體。',
         vocab=[('memorandum (n.)', '「備忘錄」，複數 memoranda，MOU 即 memorandum of understanding。'),
                ('vehicle (n.)', '金融術語「載體、工具」，financing vehicle 指專為融資設立的實體。'),
                ('depreciate (v.)', '「折舊、貶值」，名詞 depreciation。')]),
    dict(title_en='The Great Unbundling of Consumer Fintech',
         title_zh='消費金融科技的大解綁',
         gist_en="AI agents will weaken the traditional bundling model by making product discovery, switching and financial admin dramatically easier. That opens room for neutral AI-native platforms that sit above a user's whole financial stack, analyse continuously, recommend better products and execute the moves.",
         body_zh='AI agent 會讓「找產品、換供應商、處理財務庶務」這些事變得容易太多，進而削弱傳統消費金融科技那套把服務綁在一起的模式。這也為「中立的 AI 原生平台」開出空間：它們凌駕在使用者整個財務體系之上，持續分析財務狀況、推薦更好的產品，並實際執行轉帳、貸款轉貸、更換供應商與各種行政流程。',
         vocab=[('unbundling (n.)', '「解綁」，把原本包在一起的服務拆開，反義 bundling。'),
                ('sit above X', '片語「位於 X 之上」，架構描述常用。'),
                ('execute (v.)', '「執行」，此處指實際完成動作而非僅提出建議。')]),
    dict(title_en='Robinhood’s Second Private Markets Fund Starts Trading',
         title_zh='Robinhood 第二檔私募市場基金掛牌',
         gist_en="Robinhood Ventures Fund II debuted on the NYSE after raising $225.5 million, giving retail investors exposure to early and growth-stage private companies. The launch extends the firm's push into private markets following its first late-stage venture fund.",
         body_zh='Robinhood Ventures Fund II 募得 2.255 億美元後在紐約證交所掛牌，讓一般散戶也能參與早期與成長期私人公司的投資，重點放在現任與過去的 Y Combinator 新創。這次上市延續了該公司繼首檔後期創投基金之後，持續進軍私募市場的策略，公司也正籌備更多基金，希望擴大散戶接觸新創投資的管道。',
         vocab=[('debut (v.)', '「首次登場、掛牌」，源自法文，發音為 /deɪˈbjuː/。'),
                ('retail investor', '「散戶投資人」，與機構投資人相對。'),
                ('push into X', '片語「進軍 X 領域」，push 作名詞指這股推進力。')]),
    dict(title_en='An AI-Driven Challenger in the ETF Fee War',
         title_zh='用 AI 打價格戰的 ETF 挑戰者',
         gist_en="An insurance-backed ETF arm has launched 197 funds since December and expects to pass the largest incumbent on total US ETF count by year-end, using AI to speed regulatory filings and launches. It is also undercutting rivals on fees, betting lower costs and a vertically integrated float strategy win assets over time.",
         body_zh='金融科技新創 Corgi Insurance 旗下的 ETF 部門 Corgi Invest，自去年 12 月以來已推出 197 檔 ETF，預計年底前在美國 ETF 總檔數上超越貝萊德，靠的是用 AI 加速法規申報與產品上市流程。該公司同時在緩衝收益型、槓桿型與單一個股 ETF 上以更低費用搶市，賭的是「低成本＋垂直整合的保險浮存金策略」能隨時間累積資產規模。',
         vocab=[('incumbent (n.)', '「現任者、既有龍頭」，商業上指市場既得地位者。'),
                ('undercut (v.)', '「以更低價搶market」，過去式與過去分詞同形 undercut。'),
                ('float (n.)', '保險術語「浮存金」，指保費收入到理賠支出之間可運用的資金。')]),
    dict(title_en='What Capital Wants',
         title_zh='資本到底想要什麼',
         gist_en="Fundraising has shifted toward a team-plus-market view, where investors ask whether a company can become the clear winner in a market big enough to support a $20 billion outcome. With sector mandates fading, founders must find true believers or position inside themes capital already believes it must own.",
         body_zh='新創募資已轉向一種「團隊加上市場規模」的評估方式：投資人越來越常問的是，這家公司能不能在一個「大到足以撐起 200 億美元結果」的市場中成為明確的贏家。隨著傳統依產業別劃分的投資授權逐漸淡出，創辦人現在得去找到真正相信自己的投資人、教育市場理解一個確實新穎的機會，或是把自己放進資本圈「已經認定非投不可」的主題裡。',
         vocab=[('mandate (n.)', '「投資授權範疇」，指基金被允許投資的領域。'),
                ('fade (v.)', '「逐漸消退」，此處指某做法失去主導地位。'),
                ('true believer', '慣用語「真正的信徒」，指打從心底認同的人。')]),
    dict(title_en='A Prediction Market Cracks Down on Insider Trading',
         title_zh='預測市場出手打擊內線交易',
         gist_en="A federally regulated exchange says its surveillance flagged suspicious bets involving a former congressman and a White House staffer, with cases referred to the regulator. Meanwhile a media company is building a rival prediction product and selling rapid access to posts that could move markets.",
         body_zh='這家受聯邦監管的交易所表示，監控系統已標記出多筆可疑下注，牽涉前國會議員 George Santos 與一名白宮讀稿機操作員等人，案件已轉交 CFTC。與此同時，Trump Media 正在開發 TruthPredict，並販售「快速取得可能撼動金融市場的 Truth Social 貼文」的權限。小唐納‧川普本身既擔任 Kalshi 顧問，又與競爭對手 Polymarket 有牽連，使得總統職位與這些可交易政治資訊的平台之間形成異常緊密的關係。',
         vocab=[('crack down on X', '片語「嚴厲取締 X」，名詞形式為 crackdown。'),
                ('flag (v.)', '「標記為可疑」，監控系統常用動詞。'),
                ('refer X to Y', '「將 X 移送給 Y 處理」，行政與法律程序用語。')]),
    dict(title_en='Talks to Acquire PayPal Are Heating Up',
         title_zh='收購 PayPal 的談判正在升溫',
         gist_en="Stripe and a private equity partner are reportedly still negotiating a PayPal acquisition after an initial offer valued the company at roughly $53 billion, with a deal possibly coming together within weeks. Talks come as PayPal pursues a turnaround including a planned 20% workforce reduction.",
         body_zh='據報導，Stripe 與 Advent 仍在洽談收購 PayPal，先前每股 60.50 美元的初步報價，把該公司估值定在約 530 億美元，交易可能在數週內成形。談判發生的背景，是執行長 Enrique Lores 正推動全面轉型，包括把 PayPal 重組為三個營運單位、重新聚焦技術與 AI，並透過裁員兩成來壓低成本。',
         vocab=[('heat up', '片語動詞「升溫、加劇」，反義 cool off。'),
                ('come together', '片語「談成、成形」，指交易或計畫最終定案。'),
                ('turnaround (n.)', '商業術語「轉虧為盈、企業翻身」。')]),
]))

TOPICS.append(dict(zh='IT 產業', en='TLDR IT', date='2026-08-19', arts=[
    dict(title_en='Growing Mac Fleets Outpace Manual Compliance',
         title_zh='Mac 機隊變大，人工合規跟不上',
         gist_en="As Mac fleets grow, manual scripts, spreadsheets and one-off remediation become hard for lean IT teams to sustain. Configuration, patching, drift detection and audit evidence need to be continuously automated rather than treated as periodic compliance projects.",
         body_zh='當公司內的 Mac 數量成長，靠人工腳本、試算表與一次性的補救處理，對人力精簡的 IT 團隊來說會越來越難維持。裝置組態、修補更新、組態飄移偵測與稽核證據，都必須變成「持續自動化」的機制，而不是每隔一段時間才做一次的合規專案。',
         vocab=[('fleet (n.)', '「機隊」，此處指公司管理的整批電腦裝置。'),
                ('drift (n.)', 'IT 術語「組態飄移」，指實際設定逐漸偏離基準值。'),
                ('remediation (n.)', '「修補、矯正」，資安與合規領域常用。')]),
    dict(title_en='Microsoft Consolidates Copilot Into One App',
         title_zh='微軟把 Copilot 整併成單一應用',
         gist_en="Microsoft began unifying its consumer and Microsoft 365 Copilot experiences ahead of a broader super-app overhaul later this quarter. Work and personal identities stay separated through different account types, and enterprise tenant controls and compliance boundaries remain intact.",
         body_zh='微軟自 8 月 18 日起，開始把消費者版與 Microsoft 365 版的 Copilot 體驗整併起來，為本季稍後更大規模的「超級應用」改版鋪路。工作與個人身分仍會透過 Microsoft 帳戶與 Entra 帳戶分開處理，企業租戶的管控與法遵邊界也維持不變。',
         vocab=[('consolidate (v.)', '「整併、合併」，名詞 consolidation。'),
                ('overhaul (n./v.)', '「徹底翻修、大改版」，語氣比 update 強烈許多。'),
                ('intact (adj.)', '「完整無損的」，remain intact 指維持原狀不受影響。')]),
    dict(title_en='The Browser Is Now the Primary Endpoint',
         title_zh='瀏覽器已經是企業的主要端點',
         gist_en="With more work happening inside SaaS apps, the browser increasingly acts as the gateway between users, corporate identities and company data. Browser policy, extensions, work profiles, session controls and visibility should be treated as endpoint-management concerns.",
         body_zh='隨著越來越多工作在 SaaS 應用裡完成，瀏覽器實際上已成為使用者、公司身分與企業資料之間的通道。因此瀏覽器政策、擴充套件、工作設定檔、工作階段控管與可視性，都應該被納入「端點管理」的範疇來看待，而不是把瀏覽器當成一個沒人管的普通應用程式。',
         vocab=[('endpoint (n.)', '資安術語「端點」，指連上公司網路的使用者裝置。'),
                ('act as X', '片語「充當、扮演 X 的角色」。'),
                ('visibility (n.)', '此處為「可視性」，指管理者能掌握多少實際狀況。')]),
    dict(title_en='Mapping the Network Before Modernizing It',
         title_zh='要現代化網路，先把它盤點清楚',
         gist_en="Two vendors are combining network discovery, topology mapping and monitoring to help teams understand what infrastructure they actually have and where upgrades are needed. The approach targets mixed multi-vendor environments and helps prioritise aging hardware before heavier workloads arrive.",
         body_zh='Cisco 與 Auvik 正把網路探索、拓撲繪製與監控整合起來，幫助 IT 團隊先搞清楚自己手上到底有哪些基礎設施、哪裡需要升級。這套做法同時支援 Cisco、Meraki 與多廠牌混合環境，讓團隊在導入更吃資源的工作負載之前，能先排出老舊硬體、容量瓶頸與現代化工程的優先順序。',
         vocab=[('discovery (n.)', 'IT 術語「探索」，自動掃描並辨識網路上的裝置。'),
                ('topology (n.)', '「拓撲」，描述網路節點之間的連接結構。'),
                ('prioritise (v.)', '「排定優先順序」，美式拼法 prioritize。')]),
    dict(title_en='An Alliance Targets SaaS Cost Control',
         title_zh='聯手替中型企業控管 SaaS 支出',
         gist_en="Two firms launched an alliance to help midmarket companies control SaaS and cloud spend, pairing procurement intelligence drawn from more than $75 billion in spend with technology and cloud advisory services. The aim is to move procurement from reactive renewal haggling to continuous optimisation.",
         body_zh='Vertice 與 RSM 成立策略聯盟，協助中型企業控管 SaaS 與雲端支出：一方提供橫跨逾 750 億美元支出所累積的採購情報，另一方提供技術與雲端顧問服務。目標是把軟體採購，從「合約到期前才被動殺價」轉變成持續進行的成本與供應商最佳化。',
         vocab=[('procurement (n.)', '「採購」，企業正式用語，動詞 procure。'),
                ('renewal (n.)', '「續約」，動詞 renew。'),
                ('midmarket (n./adj.)', '「中型企業市場」，介於中小企業與大型企業之間。')]),
    dict(title_en='Cisco Closes Two More Infrastructure Acquisitions',
         title_zh='Cisco 再完成兩樁基礎架構收購',
         gist_en="Cisco disclosed it closed acquisitions covering observability and non-human identity during its latest quarter. The deals push the company further toward a combined networking, observability and identity operations platform.",
         body_zh='Cisco 揭露在最近一季完成了兩樁收購：一家專注可觀測性的 Galileo Technologies，以及一家專注「非人類身分」的 Astrix Security。這兩筆交易，讓 Cisco 更往「網路、可觀測性與身分維運三合一平台」的方向推進。',
         vocab=[('close a deal', '商業片語「完成交易」，close 在此為「結案」。'),
                ('observability (n.)', '「可觀測性」，從外部輸出推斷系統內部狀態的能力。'),
                ('non-human identity', '資安新詞「非人類身分」，指服務帳號、API 金鑰、agent 等。')]),
    dict(title_en='Google Calendar Adds Sender Blocking',
         title_zh='Google 日曆可以封鎖寄件者了',
         gist_en="Google Calendar users can now block a sender, which removes the current invitation and prevents future invites from that account. The block also applies across supported Google products, and it began rolling out to all Workspace customers.",
         body_zh='Google 日曆使用者現在可以直接封鎖寄件者：封鎖後會自動移除對方目前送出的邀請，並阻擋該 Google 帳戶未來的所有邀請。這個封鎖同時會套用到其他支援的 Google 產品上，功能自 8 月 18 日起向所有 Workspace 客戶推送。',
         vocab=[('unsolicited (adj.)', '「未經請求的、主動寄來的」，如 unsolicited email。'),
                ('roll out', '片語動詞「逐步推出」，名詞寫作 rollout。'),
                ('apply across X', '片語「適用於 X 各處」，強調範圍的一致性。')]),
    dict(title_en='Malware Turns Microsoft Services Into Its Control Channel',
         title_zh='惡意程式把微軟服務當成自己的控制中心',
         gist_en="A malware family hides its command-and-control traffic inside trusted Microsoft services, using SharePoint, Teams infrastructure, Graph and even the victim's own browser. It can steal credentials and tunnel into internal systems while much of its activity looks like legitimate Microsoft traffic.",
         body_zh='名為 TWINLOOT 的惡意程式，把自己的中繼控制流量藏進受信任的微軟服務裡，包括 SharePoint、Teams 基礎設施、Microsoft Graph，甚至利用受害者本機的 Edge 瀏覽器。它能竊取憑證並打通到內部系統的隧道，而大部分活動看起來都像是從合法的微軟基礎設施發出的，因此以「行為」與「身分」為基礎的偵測就變得格外重要。',
         vocab=[('command-and-control (C2)', '資安術語「中繼控制」，攻擊者遠端操控受害主機的通道。'),
                ('tunnel (v.)', '「打隧道」，把流量包裝在另一種協定中穿透網路界線。'),
                ('legitimate (adj.)', '「合法正當的」，資安語境常與 malicious 對比。')]),
    dict(title_en='An LLM Wiki Changed How One Writer Works',
         title_zh='一套 LLM 維基如何改變工作方式',
         gist_en="A journalist built a self-organizing knowledge base that uses LLMs to ingest articles, update Markdown pages, build timelines, surface related topics and answer questions over years of research. It saves real time and suggests new connections, though it still needs ongoing maintenance.",
         body_zh='記者 Casey Newton 打造了一套會自我組織的知識庫：由 LLM 負責吸收文章、更新 Markdown 頁面、建立時間軸、帶出相關主題，並針對累積多年的研究資料回答問題。這套系統確實省下大量查資料的時間，也常常點出他原本沒想到的關聯，但仍需要持續維護。它同時也預示了 AI 可能如何重塑個人與企業的知識管理方式。',
         vocab=[('ingest (v.)', '資料工程術語「攝入、匯入」，指把外部資料收進系統。'),
                ('surface (v.)', '「使浮現、主動帶出」，此處指系統主動提示相關內容。'),
                ('self-organizing (adj.)', '「自我組織的」，指無需人工分類即可自行形成結構。')]),
]))

TOPICS.append(dict(zh='資料工程', en='TLDR Data', date='2026-08-17', arts=[
    dict(title_en='Scratch a Simple Data Model, Find a Complex One',
         title_zh='刮開簡單的資料模型，底下全是複雜',
         gist_en="A seemingly simple data model falls apart once real-world cases appear, such as ranges, missing entries, alternate numbering, repeated sections and out-of-order text. The practical lesson is to model only the complexity the product actually needs rather than chasing perfect fidelity.",
         body_zh='一個表面上看起來很單純的資料模型，一旦碰上真實世界的狀況就會瓦解——範圍、缺漏的項目、替代編號方式、重複的章節、順序錯亂的內容都會冒出來。實用的教訓是：只針對「產品真正需要」的複雜度建模，而不是預設就追求完美還原。',
         vocab=[('break down', '片語動詞「瓦解、失效」。'),
                ('fidelity (n.)', '「忠實度、還原度」，high fidelity 指高度貼近原貌。'),
                ('chase (v.)', '此處為「一味追求」，帶有徒勞的語氣。')]),
    dict(title_en='Point Lookups on the Lakehouse',
         title_zh='湖倉上的單點查詢',
         gist_en="Metadata-table indexes make selective lakehouse reads behave more like database lookups than full scans. Record-level, secondary, expression and bloom-filter indexes can prune equality predicates down to just a few files.",
         body_zh='Apache Hudi 的中繼資料表索引，讓湖倉中的選擇性讀取表現得更像資料庫的單點查詢，而不是整批全表掃描。記錄層級索引、次要索引、運算式索引與布隆過濾器索引，都能把等值條件的搜尋範圍裁剪到只剩少數幾個檔案。',
         vocab=[('lookup (n.)', '「查找」，point lookup 指依主鍵取出單筆資料。'),
                ('prune (v.)', '「修剪、削減」，查詢最佳化上指排除不需掃描的資料。'),
                ('predicate (n.)', '資料庫術語「述詞」，即 WHERE 子句中的條件判斷。')]),
    dict(title_en='Why AI Is a Storage Workload',
         title_zh='為什麼 AI 其實是一種儲存工作負載',
         gist_en="AI inference is becoming stateful infrastructure: long-context sessions, agents, retrieval and multimodal work create durable caches, prefixes, memories and embeddings that cost less to store than to recompute. The storage hierarchy is moving into the hot path.",
         body_zh='AI 推論正逐漸變成「有狀態」的基礎設施：長上下文的工作階段、agent、檢索增強生成與多模態流程，都會產生需要保存的 KV 快取、前綴、記憶與嵌入向量，而這些東西只要重複使用夠多次，存起來就比重算划算。於是整個儲存階層（HBM、DRAM、SSD、物件儲存、CXL 與快閃層）被推進系統的關鍵路徑，直接左右延遲與成本。',
         vocab=[('stateful (adj.)', '「有狀態的」，系統會記住先前互動，反義 stateless。'),
                ('recompute (v.)', '「重新計算」，re-＋compute，與 store（儲存）形成取捨。'),
                ('hot path', '效能術語「關鍵路徑」，最頻繁執行、最影響效能的程式路徑。')]),
    dict(title_en='Change Data Capture Does Not Solve Dual Writes',
         title_zh='CDC 解決不了「雙重寫入」',
         gist_en="CDC makes downstream writes retryable, ordered and observable, but it does not make the destination safe to write twice. The destination still needs durable idempotency or a way to reject duplicates after recovery.",
         body_zh='CDC（異動資料擷取）能讓下游的寫入變得可重試、有順序、可觀察，但這並不代表目的端系統就能安全地被寫入兩次。目的端仍然需要具備持久的「冪等性」，或是有辦法在系統復原後拒絕重複資料。對那些把 CDC 當成「自動解決一致性」的團隊來說，這是個很值得拿來檢視自家設計的角度。',
         vocab=[('idempotency (n.)', '「冪等性」，同一操作執行多次結果不變的特性。'),
                ('downstream (adj.)', '「下游的」，指資料流向的後段系統。'),
                ('duplicate (n.)', '「重複項」，動詞則為「複製」，重音位置不同。')]),
    dict(title_en='On Benchmarking',
         title_zh='談基準測試這件事',
         gist_en="A throughput number is not an architecture decision. Good benchmarks explain the workload, cache state, client behaviour, failure modes and scaling limit behind the result, or teams end up optimising for a synthetic score instead of real bottlenecks.",
         body_zh='一個吞吐量數字本身，並不構成架構決策。好的基準測試會交代清楚這個數字背後的工作負載、快取狀態、客戶端行為、失效模式與擴展極限。缺少這些脈絡，團隊很容易把力氣花在優化一個人造分數上，而不是處理正式環境真正會遇到的瓶頸。',
         vocab=[('throughput (n.)', '「吞吐量」，單位時間內能處理的工作量。'),
                ('synthetic (adj.)', '「人造的、合成的」，此處指非真實情境產生的數據。'),
                ('failure mode', '工程術語「失效模式」，系統故障時的具體表現方式。')]),
    dict(title_en='Agentic Engineering With Humans Still in Control',
         title_zh='人還在方向盤上的 Agentic 工程',
         gist_en="One engineer uses coding agents at high volume while keeping humans in charge of design, review and final decisions. Detailed specs, adversarial reviews and continuous verification let three engineers ship hundreds of pull requests weekly without relying on autonomous loops.",
         body_zh='Kenn 大量使用編碼 agent，但把設計、審查與最終決策牢牢留在人手上。靠著詳盡的規格、對抗式審查與持續驗證，三名工程師就能每週送出數百個 PR，而且完全不依賴放任式的自主迴圈。',
         vocab=[('in charge of X', '片語「負責掌管 X」。'),
                ('adversarial (adj.)', '「對抗性的」，adversarial review 指刻意挑毛病的審查。'),
                ('autonomous loop', '「自主迴圈」，指 AI 無人監督地反覆執行。')]),
    dict(title_en='Tracking Down a 16-Year-Old SQLite Bug',
         title_zh='追出一個潛伏十六年的 SQLite 臭蟲',
         gist_en="A team spent six months tracing repeated database corruption to a rare 16-year-old race condition between checkpointing and write transactions, made more likely by aggressive manual checkpointing. The lesson is that even boring technology gets risky when operated outside its common paths.",
         body_zh='Tailscale 花了六個月，才把反覆出現的 SQLite 資料損毀，追溯到一個潛伏十六年、極少觸發的競爭條件——問題出在 WAL 檢查點機制與寫入交易之間，而他們過於積極的手動檢查點作法讓它更容易發生。這場調查最終促成 SQLite 官方修補與更強的復原工具，也留下一個更普遍的教訓：即使是「無聊到不會出事」的成熟技術，一旦被用在偏離常規的路徑上，同樣充滿風險。',
         vocab=[('race condition', '「競爭條件」，多個執行緒同時存取共享資源導致的不確定錯誤。'),
                ('corruption (n.)', '「（資料）損毀」，動詞 corrupt。'),
                ('boring (adj.)', '此處為工程圈的褒義用法，指成熟穩定、少有意外的技術。')]),
    dict(title_en='Apache DataFusion Comet Reaches 1.0',
         title_zh='Apache DataFusion Comet 推出 1.0',
         gist_en="Comet, a Spark accelerator, reached 1.0 with semantic versioning, Spark 4 support, broader operator coverage and extensive correctness testing against Spark's own suite. It targets teams wanting faster execution without rewriting jobs or replacing the surrounding ecosystem.",
         body_zh='建構在 Apache DataFusion 之上的 Spark 加速器 Comet 推出 1.0 版，採用語意化版本管理、支援 Spark 4、擴大運算子涵蓋範圍，並針對 Spark 自身的測試套件做了大量正確性驗證。它鎖定的族群是「想讓 Spark 跑更快，但不想重寫作業、也不想換掉周邊生態系」的團隊。',
         vocab=[('accelerator (n.)', '「加速器」，此處指提升既有系統執行速度的元件。'),
                ('coverage (n.)', '「涵蓋範圍」，operator coverage 指支援多少種運算子。'),
                ('correctness (n.)', '「正確性」，軟體測試的核心指標之一。')]),
    dict(title_en='DataBench Tests Agents on Messy Analytics',
         title_zh='DataBench 用真實髒資料考驗 AI Agent',
         gist_en="A new benchmark puts AI agents on realistic, messy analytics tasks and finds them strong at gathering evidence but weaker at open-ended decisions where judgement matters. Models often fail by manufacturing certainty, missing subtle data traps or overthinking correct answers.",
         body_zh='Hex 推出的 DataBench，用貼近現實、資料髒亂的分析任務來測試 AI agent，結果發現它們很擅長蒐集證據，但一遇到需要判斷力的開放式決策就明顯變弱。常見的失敗方式包括：憑空製造出過度的確定感、漏看資料中不明顯的陷阱，或是對本來就答對的題目想太多。這也說明為什麼複雜分析工作仍然需要人來覆核。',
         vocab=[('messy (adj.)', '「雜亂的」，資料科學常用來形容未清理的真實資料。'),
                ('open-ended (adj.)', '「開放式的」，沒有唯一標準答案。'),
                ('manufacture (v.)', '此處為「捏造」，manufacturing certainty 指硬生出確定感。')]),
    dict(title_en='What’s New in OpenSearch 3.8',
         title_zh='OpenSearch 3.8 有什麼新東西',
         gist_en="OpenSearch 3.8 improves vector ingestion, radial query throughput and median query latency while expanding agent support. Tool discovery is richer, streaming inference lowers token latency, and analytics teams get new query tooling and one-click alerts.",
         body_zh='OpenSearch 3.8 改善了向量資料匯入、放射狀查詢吞吐量與查詢延遲中位數，同時擴大對 AI agent 的支援：MCP 現在適用於所有 agent 類型，工具探索功能更完整，gRPC 串流推論則降低了 token 延遲。分析團隊另外獲得新的 PPL/SQL 工具、Grok 除錯、一鍵 Prometheus 警示，以及搜尋相關性工作流程的改進。',
         vocab=[('ingestion (n.)', '「匯入、攝取」，指資料進入系統的第一道流程。'),
                ('median (n.)', '統計術語「中位數」，與 mean（平均數）不同。'),
                ('latency (n.)', '「延遲」，從發出請求到收到回應的時間。')]),
    dict(title_en='A 149 GB Query That Scanned Negative Bytes',
         title_zh='一個掃描出負數位元組的 149GB 查詢',
         gist_en="Unloading query-history data to Parquet can corrupt values when large numbers are written as 32-bit integers. Casting the affected columns before export prevents overflow, bad joins and incorrect analysis.",
         body_zh='把 Snowflake 的 QUERY_HISTORY 資料卸載成 Parquet 時，如果數值太大卻被寫成 INT32，就可能造成數值損毀，出現「掃描 -1.5GB」這種荒謬結果。只要在匯出前先把受影響的九個欄位做型別轉換，就能避免溢位、錯誤的表格連結與後續分析失準。',
         vocab=[('unload (v.)', '資料工程術語「卸載、匯出」。'),
                ('overflow (n.)', '「溢位」，數值超出型別可表示範圍。'),
                ('cast (v.)', '程式術語「型別轉換」，把資料從一種型別轉成另一種。')]),
    dict(title_en='Fairly Ranking the Most Brilliant Birds',
         title_zh='怎樣才算公平地替鳥類的鮮豔程度排名',
         gist_en="A transparent ranking of the world's most brilliant birds combines chroma, colour variety, sample confidence and diversity. The larger point is that ranking systems are fairest when every factor is understandable, defensible and tied to a reasonable human judgement.",
         body_zh='一份公開透明的「全球最鮮豔鳥類」排行榜，綜合了色度、色彩多樣性、樣本信賴度與多樣性等指標，最終由橙胸鵐奪冠。但文章想講的重點其實更大：一套排名系統要稱得上公平，前提是每一個評分因子都能被理解、站得住腳，並且對應到合理的人類判斷。',
         vocab=[('chroma (n.)', '色彩學術語「色度」，描述顏色的純度與飽和度。'),
                ('defensible (adj.)', '「站得住腳的」，指經得起質疑與辯護。'),
                ('tied to X', '片語「與 X 相繫」，此處指評分依據要對應到實際judgment。')]),
]))

TOPICS.append(dict(zh='硬體', en='TLDR Hardware', date='2026-08-19', arts=[
    dict(title_en='Etched Doubles Its Valuation Again to $21B',
         title_zh='Etched 估值再翻倍至 210 億美元',
         gist_en="Etched raised $700 million at a $21 billion valuation, a month after closing a $10.3 billion round. The jump is backed by real deployment: the lead investor tested and bought the hardware before investing and has put its first inference cluster rack into production.",
         body_zh='Etched 以 210 億美元估值募得 7 億美元，由 Jane Street 領投，距離上一輪 103 億美元估值才過一個月，而去年 12 月時估值還只有 50 億。這次跳升背後有真實部署撐腰：Jane Street 是先測試並實際採購 Etched 硬體之後才投資，如今已把第一座「前沿推論叢集」機櫃投入自家資料中心運作。Etched 主打兩項為推論訂製的元件，並已放棄原本「把特定模型蝕刻進矽晶片」的構想，改為支援任何前沿模型。',
         vocab=[('valuation (n.)', '「估值」，新創募資的核心數字。'),
                ('back (v.)', '此處為「支撐、佐證」，backed by real deployment 指有實際部署為證。'),
                ('walk back (v. phr.)', '片語「收回、修正先前說法或計畫」。')]),
    dict(title_en='Google Reportedly Taps AMD for a Next-Generation TPU',
         title_zh='傳 Google 找上 AMD 共同設計新一代 TPU',
         gist_en="Google is reportedly working with AMD on a tenth-generation TPU variant with on-package CPU cores and advanced 3D packaging. The hybrid design targets reinforcement learning, reasoning and agentic workloads that need low latency and a higher CPU-to-accelerator ratio than standard pipelines.",
         body_zh='據報導，Google 正與 AMD 合作開發第十代 TPU 的變體版本，特色是把 CPU 核心整合進同一封裝，並採用先進 3D 封裝技術。Google 仍維持與 Broadcom 在傳統 AI 加速器上的長期合作，但這款混合設計預計會借重 AMD 的 x86 CPU 矽智財與 SoIC 封裝經驗，把通用運算直接擺在 TPU 矩陣引擎旁邊。此架構轉向鎖定的是強化學習、推理與 agentic 工作負載——這些任務需要低延遲，且對 CPU 與加速器的比例要求高於一般 LLM 流程。',
         vocab=[('tap (v.)', '此處為「找上、延攬」，tap X for Y 指找 X 來做 Y。'),
                ('on-package (adj.)', '半導體術語「同封裝內的」，指整合在同一封裝基板上。'),
                ('variant (n.)', '「變體、衍生版本」。')]),
    dict(title_en='Cerebras Pitches Wafer-Scale Against Multi-GPU Clusters',
         title_zh='Cerebras 用晶圓級晶片對打多 GPU 叢集',
         gist_en="Cerebras announced its next-generation wafer-scale system, claiming substantial speed and throughput advantages over flagship accelerators. Building around a single-wafer processor removes inter-chip interconnect bottlenecks, delivering very low latency and higher tokens per second for large models.",
         body_zh='Cerebras 發表新一代晶圓級 AI 超級運算系統，宣稱在速度與吞吐量上都大幅領先 Nvidia 旗艦加速器。由於整套機器建構在單一晶圓處理器架構上，直接消除了晶片之間互連所造成的瓶頸，因此能為大型語言模型帶來極低延遲與更高的每秒 token 數。這次推出讓資料中心 AI 基礎設施的競爭更加白熱化，Cerebras 主打自家特化的晶圓級矽晶片，是比傳統多 GPU 叢集更高效能、更省電的選項。',
         vocab=[('wafer-scale (adj.)', '半導體術語「晶圓級的」，整片晶圓做成單一晶片。'),
                ('interconnect (n.)', '「互連」，晶片或節點之間的資料通道。'),
                ('bottleneck (n.)', '「瓶頸」，此處指互連頻寬限制整體效能。')]),
    dict(title_en='Nvidia Books TSMC 1.6nm Capacity for 2028',
         title_zh='Nvidia 預訂台積電 1.6 奈米產能，鎖定 2028',
         gist_en="Nvidia has reserved advanced capacity on TSMC's 1.6nm node for its next-generation architecture, slated for production in the second half of 2028. The process combines nanosheet transistors with backside power delivery, offering gains in logic density, power efficiency and signal routing.",
         body_zh='Nvidia 已在台積電 1.6 奈米（A16）製程上預訂先進產能，供代號「Feynman」的下一代架構使用，預計 2028 年下半年投產。A16 製程結合奈米片電晶體與背面供電網路，在邏輯密度、功耗效率與訊號繞線上都有顯著提升。提早卡位晶圓代工產能，等於也把自家長期硬體路線圖鎖定下來。',
         vocab=[('reserve (v.)', '「預訂、保留」，此處指預先鎖定製造產能。'),
                ('slated for X', '片語「預定於 X」，常見於產品時程報導。'),
                ('lock in (v. phr.)', '片語「鎖定、確保」，lock in capacity 指確保產能。')]),
    dict(title_en='Liquid Cooling Needs Fluid-Side Observability',
         title_zh='液冷時代，要看的不只是晶片溫度',
         gist_en="As liquid cooling becomes standard, heat travels through a whole chain rather than staying inside the server, so trouble anywhere along that path can quietly eat a chip's thermal margin. Component temperature alone only confirms a chip is within limits; it never shows how hard the control system is working to hold it there.",
         body_zh='隨著液冷成為高功耗 AI 加速器的標配，熱量不再只留在伺服器內部，而是沿著冷板、分歧管、軟管、冷卻分配裝置一路走到廠房散熱端。這條路徑上任何一處出問題，都可能在溫度警報響起之前，悄悄吃掉晶片的散熱餘裕。只看元件溫度，充其量只能確認晶片「目前」還在容許範圍內，卻看不出控制系統為了維持這個溫度有多吃力、還剩多少餘裕——因為幫浦與閥門本來就會默默地替你補償正在惡化的問題。',
         vocab=[('margin (n.)', '「餘裕、安全邊際」，thermal margin 指散熱上的緩衝空間。'),
                ('compensate (v.)', '「補償、抵銷」，此處指系統自動彌補異常。'),
                ('quietly (adv.)', '「悄悄地」，強調問題在無聲無息中累積。')]),
    dict(title_en='800VDC Pushes AI Power Design From Grid to Gate',
         title_zh='800 伏直流：從電網一路重寫到閘極',
         gist_en="AI datacenters are weighing a move to 800VDC distribution. Stepping away from 48V streamlines the conversion path from medium-voltage grid AC down to sub-1V silicon, cutting conversion heat losses and heavy copper cabling, but it depends on silicon carbide and gallium nitride devices and upgraded DC-rated switchgear.",
         body_zh='AI 資料中心正在評估改用 800V 直流配電架構。捨棄現行的 48V 配電，可以簡化「從中壓交流電網一路降到 1V 以下矽晶片」的整條轉換路徑，減少轉換過程的熱損耗，也大幅降低粗重銅纜的需求。不過要真正實現這種「從電網到閘極」的效率，得仰賴碳化矽（SiC）與氮化鎵（GaN）功率半導體、固態變壓器，以及能承受直流的升級版開關設備，才能在 AI 叢集中安全處理高壓與快速負載切換。這些技術雖然成熟得很快，但要改變資料中心的既有設計，恐怕仍需數年。',
         vocab=[('distribution (n.)', '此處為電力術語「配電」，power distribution。'),
                ('conversion (n.)', '「轉換」，指電壓在不同層級之間的變換。'),
                ('switchgear (n.)', '電力工程術語「開關設備」，用於控制與保護電路。')]),
    dict(title_en='The Tech War Reaches AI’s Plumbing',
         title_zh='科技戰打到 AI 的「水管」層級',
         gist_en="A reported ban on Chinese optical transceivers shows the tech war expanding past chips into the smallest links of AI's physical plumbing. Concern centres on data theft, disruption and long-term dependence, but a sudden ban risks backfiring because domestic suppliers cannot match the scale.",
         body_zh='傳出 FCC 將禁用中國製光收發模組，顯示美中科技戰已從晶片延伸到 AI 實體網路中最細微的環節。華府的疑慮集中在資料竊取、服務中斷與長期依賴——因為這些模組實體嵌在網路各處，理論上可能夾帶惡意程式。但突然禁用也可能反噬：美國供應商的產能規模跟不上中國，若被迫短時間內替換，亞馬遜、微軟等超大規模業者將面臨實質的供應中斷。',
         vocab=[('plumbing (n.)', '原意「水管配管」，科技語境引申為底層基礎管線。'),
                ('transceiver (n.)', '「收發器」，transmitter＋receiver 的合成字。'),
                ('backfire (v.)', '「適得其反、反噬」，原指槍砲回火。')]),
    dict(title_en='China’s Hardware Exports Offer a Cleaner Demand Signal',
         title_zh='中國硬體外銷提供了比較乾淨的需求訊號',
         gist_en="US AI investment has become dangerously circular, with suppliers financing customers who spend that capital back on the suppliers' own hardware, blurring real end-user demand. China's push into overseas industrial AI hardware gives a cleaner signal, because a robot installed on a foreign factory floor can be checked against customs data.",
         body_zh='美國的 AI 投資已經陷入危險的「循環」：供應商出資給客戶，客戶再拿這筆錢回頭買供應商自家的硬體，導致真實的終端需求與金融操作難以區分。相較之下，中國積極把工業 AI 硬體、機器人、資料中心設備與自動化產線外銷海外，反而提供了比較乾淨的訊號——因為一台實際運到國外、裝在工廠地板上的機器人，可以用海關資料與生產數量去驗證，而不是藏在內部融資的迴圈裡。',
         vocab=[('circular (adj.)', '「循環的」，此處指資金在同一圈子內打轉的可疑結構。'),
                ('blur (v.)', '「使模糊」，此處指難以分辨真實需求。'),
                ('signal (n.)', '「訊號」，經濟分析中指可據以判斷實情的證據。')]),
]))
